site_name: OTCv8 Dev — Dokumentacja
site_url: https://lukaszj321.github.io/otcv8-dev/

theme:
  name: material
  language: pl
  logo: _assets/img/logo.svg
  favicon: _assets/img/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
  font:
    text: Roboto
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: blue
      accent: indigo

repo_url: https://github.com/lukaszj321/otcv8-dev
repo_name: lukaszj321/otcv8-dev
edit_uri: edit/master/docs/

use_directory_urls: true

extra_css:
  - _assets/css/title-fix.css

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  - redirects
  - exclude:
      glob:
        # === TNIEMY WSZYSTKO, CO JEST ciężkie albo zbędne w buildzie ===
        - '**/__pycache__/**'
        - '**/.DS_Store'
        - '**/*.zip'
        - '**/*.7z'
        - '**/*.tar'
        - '**/*.tar.gz'
        - '**/*.tgz'
        - '**/*.rar'
        - '**/downloads/**'
        - 'downloads/**'
        - '**/download/**'
        - '**/backup/**'
        - '**/__old__/**'
        - '**/archive/**'
        - 'docs/modules/**/__md_backup_*.md'
        - 'docs/modules/**/__md_backup_*/**'
        - 'docs/modules/__md_backup_*/**'
        # Jeśli te działy nie są Ci teraz potrzebne w menu, wytnij je z budowania (przyspiesza):
        - 'docs/build/**'
        - 'docs/cpp/**'
        - 'docs/data/**'
        - 'docs/dev/**'
        - 'docs/guides/**'
        - 'docs/knowledge/**'
        - 'docs/lua/**'
        - 'docs/tools/**'
        - 'docs/ui/**'
        # jeśli chcesz – możesz też tymczasowo wyłączyć ciężkie API:
        # - 'docs/api/**'

markdown_extensions:
  - toc:
      permalink: true
      separator: '-'
  - tables
  - fenced_code
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.emoji:
      # FIX emoji – nowa przestrzeń nazw, bez „materialx.emoji”
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Mała, bezpieczna nawigacja — szybka i pewna
nav:
  - Start: index.md
  - Modules:
      - INDEX: modules/structured/INDEX.md
      - Core:
          - INDEX: modules/structured/core/INDEX.md
      - Gameplay:
          - INDEX: modules/structured/gameplay/INDEX.md
      - Dev tools:
          - INDEX: modules/structured/dev_tools/INDEX.md

validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    absolute_links: warn
    unrecognized_links: warn
    anchors: warn
