site_name: "OTCv8 Dev — Dokumentacja"
site_url: "https://lukaszj321.github.io/otcv8-dev/"

repo_url: "https://github.com/lukaszj321/otcv8-dev"
repo_name: "lukaszj321/otcv8-dev"
edit_uri: "edit/master/docs/"

theme:
  name: material
  language: pl
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
  font:
    text: Roboto
    code: Fira Code
  logo: "_assets/img/logo.svg"
  favicon: "_assets/img/favicon.png"
  palette:
    - scheme: default
      primary: blue
      accent: indigo

nav:
  - Start: index.md
  - Modules:
    - INDEX: modules/structured/INDEX.md
    - Core:
      - INDEX: modules/structured/core/INDEX.md
    - Gameplay:
      - INDEX: modules/structured/gameplay/INDEX.md
    - Dev tools:
      - INDEX: modules/structured/dev_tools/INDEX.md

extra_css:
  - "_assets/css/title-fix.css"

markdown_extensions:
  - toc:
      permalink: true
      separator: "-"
  - tables
  - fenced_code
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - exclude:
      # WYTNIE WSZYSTKO oprócz index.md i katalogu modules/**
      regex:
        - '^(?!index\.md$)(?!modules/).*'
  # Jak będziesz chciał daty commitów, ustaw ENABLE_GIT_DATES=1 w workflow
  - git-revision-date-localized:
      enabled: !ENV [ENABLE_GIT_DATES, false]

strict: false
