site_name: "OTCv8 Dev — Dokumentacja"
site_url: "https://lukaszj321.github.io/otcv8-dev/"

repo_url: "https://github.com/lukaszj321/otcv8-dev"
repo_name: "lukaszj321/otcv8-dev"
edit_uri: "edit/master/docs/"

theme:
  name: material
  language: pl
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
  font:
    text: Roboto
    code: Fira Code
  logo: "_assets/img/logo.svg"
  favicon: "_assets/img/favicon.png"
  palette:
    - scheme: default
      primary: blue
      accent: indigo

nav:
  - Start: index.md
  - Modules:
    - INDEX: modules/structured/INDEX.md
    - Core:
      - INDEX: modules/structured/core/INDEX.md
    - Gameplay:
      - INDEX: modules/structured/gameplay/INDEX.md
    - Dev tools:
      - INDEX: modules/structured/dev_tools/INDEX.md

extra_css:
  - "_assets/css/title-fix.css"

markdown_extensions:
  - toc:
      permalink: true
      separator: "-"
  - tables
  - fenced_code
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.emoji:
      # naprawa deprecated materialx.emoji.*
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - material/search
  - redirects
  - exclude
  # ten plugin będzie DOMYŚLNIE WYŁĄCZONY na CI, żeby build był szybszy i bez ostrzeżeń;
  # chcesz daty commitów? ustaw w workflow ENV: ENABLE_GIT_DATES=1
  - git-revision-date-localized:
      enabled: !ENV [ENABLE_GIT_DATES, false]

extra:
  search:
    exclude:
      - "modules/**/__md_backup_*.md"

strict: false
