site_name: OTCv8 Dev — Dokumentacja
site_url: https://lukaszj321.github.io/otcv8-dev/
repo_url: https://github.com/lukaszj321/otcv8-dev
repo_name: lukaszj321/otcv8-dev

use_directory_urls: true

theme:
  name: material
  language: pl
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - header.autohide
  palette:
    - scheme: default
      primary: blue
      accent: indigo
  font:
    text: Roboto
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
  logo: _assets/img/logo.svg
  favicon: _assets/img/favicon.png

extra_css:
  - _assets/css/title-fix.css

plugins:
  - search
  - glightbox
  - macros
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      separator: "-"
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Start: index.md

  - Architektura:
    - Przegląd klienta: architektura/client_overview.md
    - Przegląd frameworka: architektura/framework_overview.md
    - Struktura źródeł (client/): architektura/src_client.md
    - Struktura źródeł (framework/): architektura/src_framework.md
    - C++ overview: cpp/overview.md

  # Stary zestaw (legacy)
  - Moduły:
    - Część 1: modules/modules_game_1.md
    - Część 2: modules/modules_game_2.md
    - Rdzeń modułów: modules/modules_core.md
    - Różne: modules/modules_misc.md
    - Dokumentacja modułów (zbiór): modules/modules_Documentation.md

  # Nowy, automatycznie rozbity zestaw — pełne grupowanie
  - Moduły (nowy podział):
    - Przegląd: modules/structured/README.md
    - Indeks: modules/structured/INDEX.md
    - Rdzeń (core):
      - client: modules/structured/core/modul-client.md
      - corelib: modules/structured/core/modul-corelib.md
      - gamelib: modules/structured/core/modul-gamelib.md
    - Gameplay:
      - game_actionbar: modules/structured/gameplay/modul-game_actionbar.md
      - game_battle: modules/structured/gameplay/modul-game_battle.md
      - game_console: modules/structured/gameplay/modul-game_console.md
      - game_containers: modules/structured/gameplay/modul-game_containers.md
      - game_cooldown: modules/structured/gameplay/modul-game_cooldown.md
      - game_healthinfo: modules/structured/gameplay/modul-game_healthinfo.md
      - game_hotkeys: modules/structured/gameplay/modul-game_hotkeys.md
      - game_imbuing: modules/structured/gameplay/modul-game_imbuing.md
      - game_interface: modules/structured/gameplay/modul-game_interface.md
      - game_interface/styles: modules/structured/gameplay/modul-game_interface-styles.md
      - game_interface/widgets: modules/structured/gameplay/modul-game_interface-widgets.md
      - game_inventory: modules/structured/gameplay/modul-game_inventory.md
      - game_itemselector: modules/structured/gameplay/modul-game_itemselector.md
      - game_market: modules/structured/gameplay/modul-game_market.md
      - game_market/ui: modules/structured/gameplay/modul-game_market-ui.md
      - game_market/ui/general: modules/structured/gameplay/modul-game_market-ui-general.md
      - game_market/ui/marketoffers: modules/structured/gameplay/modul-game_market-ui-marketoffers.md
      - game_market/ui/myoffers: modules/structured/gameplay/modul-game_market-ui-myoffers.md
      - game_minimap: modules/structured/gameplay/modul-game_minimap.md
      - game_modaldialog: modules/structured/gameplay/modul-game_modaldialog.md
      - game_npctrade: modules/structured/gameplay/modul-game_npctrade.md
      - game_outfit: modules/structured/gameplay/modul-game_outfit.md
      - game_playerdeath: modules/structured/gameplay/modul-game_playerdeath.md
      - game_playermount: modules/structured/gameplay/modul-game_playermount.md
      - game_playertrade: modules/structured/gameplay/modul-game_playertrade.md
      - game_prey: modules/structured/gameplay/modul-game_prey.md
      - game_questlog: modules/structured/gameplay/modul-game_questlog.md
      - game_ruleviolation: modules/structured/gameplay/modul-game_ruleviolation.md
      - game_shop: modules/structured/gameplay/modul-game_shop.md
      - game_skills: modules/structured/gameplay/modul-game_skills.md
      - game_spelllist: modules/structured/gameplay/modul-game_spelllist.md
      - game_stats: modules/structured/gameplay/modul-game_stats.md
      - game_textmessage: modules/structured/gameplay/modul-game_textmessage.md
      - game_textwindow: modules/structured/gameplay/modul-game_textwindow.md
      - game_topbar: modules/structured/gameplay/modul-game_topbar.md
      - game_unjustifiedpoints: modules/structured/gameplay/modul-game_unjustifiedpoints.md
      - game_viplist: modules/structured/gameplay/modul-game_viplist.md
      - game_walking: modules/structured/gameplay/modul-game_walking.md
    - Bot tools:
      - game_bot: modules/structured/bot_tools/modul-game_bot.md
      - default_configs / cavebot_1.3:
        - opis: modules/structured/bot_tools/modul-game_bot-default_configs-cavebot_1.3.md
        - cavebot: modules/structured/bot_tools/modul-game_bot-default_configs-cavebot_1.3-cavebot.md
        - cavebot_configs: modules/structured/bot_tools/modul-game_bot-default_configs-cavebot_1.3-cavebot_configs.md
        - targetbot: modules/structured/bot_tools/modul-game_bot-default_configs-cavebot_1.3-targetbot.md
        - targetbot_configs: modules/structured/bot_tools/modul-game_bot-default_configs-cavebot_1.3-targetbot_configs.md
      - default_configs / vBot_4.7:
        - opis: modules/structured/bot_tools/modul-game_bot-default_configs-vbot_4.7.md
        - cavebot: modules/structured/bot_tools/modul-game_bot-default_configs-vbot_4.7-cavebot.md
        - targetbot: modules/structured/bot_tools/modul-game_bot-default_configs-vbot_4.7-targetbot.md
        - vBot: modules/structured/bot_tools/modul-game_bot-default_configs-vbot_4.7-vbot.md
      - default_configs / vBot_4.8:
        - opis: modules/structured/bot_tools/modul-game_bot-default_configs-vbot_4.8.md
        - cavebot: modules/structured/bot_tools/modul-game_bot-default_configs-vbot_4.8-cavebot.md
        - targetbot: modules/structured/bot_tools/modul-game_bot-default_configs-vbot_4.8-targetbot.md
        - vBot: modules/structured/bot_tools/modul-game_bot-default_configs-vbot_4.8-vbot.md
      - functions: modules/structured/bot_tools/modul-game_bot-functions.md
      - panels: modules/structured/bot_tools/modul-game_bot-panels.md
      - ui: modules/structured/bot_tools/modul-game_bot-ui.md
    - Narzędzia developerskie:
      - client_background: modules/structured/dev_tools/modul-client_background.md
      - client_entergame: modules/structured/dev_tools/modul-client_entergame.md
      - client_feedback: modules/structured/dev_tools/modul-client_feedback.md
      - client_locales: modules/structured/dev_tools/modul-client_locales.md
      - client_mobile: modules/structured/dev_tools/modul-client_mobile.md
      - client_options: modules/structured/dev_tools/modul-client_options.md
      - client_profiles: modules/structured/dev_tools/modul-client_profiles.md
      - client_stats: modules/structured/dev_tools/modul-client_stats.md
      - client_styles: modules/structured/dev_tools/modul-client_styles.md
      - client_terminal: modules/structured/dev_tools/modul-client_terminal.md
      - client_textedit: modules/structured/dev_tools/modul-client_textedit.md
      - client_topmenu: modules/structured/dev_tools/modul-client_topmenu.md
      - corelib/ui: modules/structured/dev_tools/modul-corelib-ui.md
      - crash_reporter: modules/structured/dev_tools/modul-crash_reporter.md
      - gamelib/ui: modules/structured/dev_tools/modul-gamelib-ui.md
      - game_bugreport: modules/structured/dev_tools/modul-game_bugreport.md
      - game_buttons: modules/structured/dev_tools/modul-game_buttons.md
      - game_features: modules/structured/dev_tools/modul-game_features.md
      - game_protocol: modules/structured/dev_tools/modul-game_protocol.md
      - game_shaders: modules/structured/dev_tools/modul-game_shaders.md
      - game_things: modules/structured/dev_tools/modul-game_things.md
      - updater: modules/structured/dev_tools/modul-updater.md
    # (opcjonalnie) UI — folder istnieje, ale brak plików wg dry-run

  - API:
    - Lua:
      - Funkcje klienta (luafunctions_client.cpp): api/lua/luafunctions_client.md
    - Silnik:
      - Specyfikacja UI: api/engine/otclient_v_8_specyfikacja_ui.md
      - Presety OTUI/TS (core): api/engine/presety_kanoniczne_otui_ts_otc_core.md
      - Addendum importów z Lua (strict/golden): api/engine/otclient_v_8_addendum_import_z_lua_stringow_auto_strict_goldeny_expanded.md
      - Walidator macierzy AST & round-trip: api/engine/otclient_v_8_walidator_macierze_ast_i_round_trip_specyfikacja_techniczna.md
      - Pełna lista API (zbiorcza): api/otcv8-full-api.md

  - Dane:
    - Przewodnik: data/Data_Documentation.md

  - Przewodniki:
    - Architektura (stary przegląd): guides/architecture.md
    - Moduły (wprowadzenie): guides/modules.md
    - WebSocket: guides/websocket.md

  - Budowanie:
    - Windows: build/windows.md
    - Linux: build/linux.md
    - Android: build/android.md

  - Dev:
    - FAQ: dev/faq.md
    - Wkład (contributing): dev/contributing.md
    - Glosariusz: dev/glossary.md
    - Wydania: dev/release.md
    - Roadmapa: dev/roadmap.md
    - Bezpieczeństwo: dev/security.md
    - Testowanie: dev/testing.md
    - Troubleshooting: dev/troubleshooting.md

  - Wiedza:
    - Hot-reload module: knowledge/dev_module_for_hot_reload_master_otclient_v_8.md
    - IDE providers/spec: knowledge/ide_providers_spec_master_hover_completion_signature_help_symbols.md
    - OTUI lint rules: knowledge/otui_lint_rules_master_spec_dla_otclient_studio.md
    - AST/JSON schema: knowledge/parser_schemas_ast_json_schema_otclient_studio.md
    - QA bench suite: knowledge/qa_bench_suite_master_otclient_studio.md
    - Spec React/Electron (Studio): knowledge/specyfikacja_master_studio_react_electron_dla_otclient_v_8_v_bot_centralny_dokument.md
    - V-Bot playbook: knowledge/v_bot_playbook_modules_game_bot_master.md

  - Lua:
    - API ogólne: lua/api.md
    - Style: lua/style-guide.md

  - UI:
    - OTUI przewodnik: ui/otui.md

  - Narzędzia:
    - Przegląd: tools/tools.md
