site_name: OTCv8 Dev — Dokumentacja
site_url: https://lukaszj321.github.io/otcv8-dev/

theme:
  name: material
  language: pl
  logo: _assets/img/logo.svg
  favicon: _assets/img/favicon.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
  font:
    text: Roboto
    code: Fira Code
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/lukaszj321/otcv8-dev
repo_name: lukaszj321/otcv8-dev
edit_uri: edit/master/docs/
use_directory_urls: true

extra_css:
  - _assets/css/title-fix.css

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  - redirects
  - exclude:
      glob:
        # WYTNĘLIŚMY wszystko poza modułami + index, żeby build był szybki
        - api/**
        - build/**
        - cpp/**
        - data/**
        - dev/**
        - guides/**
        - knowledge/**
        - lua/**
        - tools/**
        - ui/**
        - modules/**/__md_backup_*/**
        - modules/__md_backup_*/**

markdown_extensions:
  - toc:
      permalink: true
      separator: '-'
  - tables
  - fenced_code
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.emoji:
      # FIX: nowe przestrzenie nazw, zero ostrzeżeń
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Minimalna, jasna nawigacja tylko do modułów
nav:
  - Start: index.md
  - Modules:
      - INDEX: modules/structured/INDEX.md
      - Core:
          - INDEX: modules/structured/core/INDEX.md
      - Gameplay:
          - INDEX: modules/structured/gameplay/INDEX.md
      - Dev tools:
          - INDEX: modules/structured/dev_tools/INDEX.md

validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    absolute_links: warn
    unrecognized_links: warn
    anchors: warn
