site_name: OTCv8 Dev — Dokumentacja
site_url: https://lukaszj321.github.io/otcv8-dev/
repo_url: https://github.com/lukaszj321/otcv8-dev
repo_name: lukaszj321/otcv8-dev

use_directory_urls: true

theme:
  name: material
  language: pl
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - header.autohide
  palette:
    - scheme: default
      primary: blue
      accent: indigo
  font:
    text: Roboto
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
  logo: _assets/img/logo.svg
  favicon: _assets/img/favicon.png

extra_css:
  - _assets/css/title-fix.css

plugins:
  - search
  - glightbox
  - macros
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      separator: "-"
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Start: index.md

  - Architektura:
    - Przegląd klienta: architektura/client_overview.md
    - Przegląd frameworka: architektura/framework_overview.md
    - Struktura źródeł (client/): architektura/src_client.md
    - Struktura źródeł (framework/): architektura/src_framework.md

  - Moduły:
    - Część 1: modules/modules_game_1.md
    - Część 2: modules/modules_game_2.md
    - Rdzeń modułów: modules/modules_core.md
    - Różne: modules/modules_misc.md
    - Dokumentacja modułów (zbiór): modules/modules_Documentation.md

  - API:
    - Lua:
      - Funkcje klienta (luafunctions_client.cpp): api/lua/luafunctions_client.md
    - Silnik:
      - Specyfikacja UI: api/engine/otclient_v_8_specyfikacja_ui.md
      - Presety OTUI/TS (core): api/engine/presety_kanoniczne_otui_ts_otc_core.md
      - Addendum importów z Lua (strict/golden): api/engine/otclient_v_8_addendum_import_z_lua_stringow_auto_strict_goldeny_expanded.md
      - Walidator macierzy AST & round-trip: api/engine/otclient_v_8_walidator_macierze_ast_i_round_trip_specyfikacja_techniczna.md

  - Dane:
    - Przewodnik: data/Data_Documentation.md

  - Przewodniki:
    - Architektura (stary przegląd): guides/architecture.md
    - Moduły (wprowadzenie): guides/modules.md
    - WebSocket: guides/websocket.md

  - Budowanie:
    - Windows: build/windows.md
    - Linux: build/linux.md
    - Android: build/android.md

  - Dev:
    - FAQ: dev/faq.md
    - Wkład (contributing): dev/contributing.md
    - Glosariusz: dev/glossary.md
    - Wydania: dev/release.md
    - Roadmapa: dev/roadmap.md
    - Bezpieczeństwo: dev/security.md
    - Testowanie: dev/testing.md
    - Troubleshooting: dev/troubleshooting.md

  - Wiedza:
    - Hot-reload module: knowledge/dev_module_for_hot_reload_master_otclient_v_8.md
    - IDE providers/spec: knowledge/ide_providers_spec_master_hover_completion_signature_help_symbols.md
    - OTUI lint rules: knowledge/otui_lint_rules_master_spec_dla_otclient_studio.md
    - AST/JSON schema: knowledge/parser_schemas_ast_json_schema_otclient_studio.md
    - QA bench suite: knowledge/qa_bench_suite_master_otclient_studio.md
    - Spec React/Electron (Studio): knowledge/specyfikacja_master_studio_react_electron_dla_otclient_v_8_v_bot_centralny_dokument.md
    - V-Bot playbook: knowledge/v_bot_playbook_modules_game_bot_master.md

  - Lua:
    - API ogólne: lua/api.md
    - Style: lua/style-guide.md

  - UI:
    - OTUI przewodnik: ui/otui.md

  - Narzędzia:
    - Przegląd: tools/tools.md
