site_name: OTCv8 Dev — Dokumentacja
site_url: https://lukaszj321.github.io/otcv8-dev/

theme:
  name: material
  language: pl
  logo: _assets/img/logo.svg
  favicon: _assets/img/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
  font:
    text: Roboto
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: blue
      accent: indigo

repo_url: https://github.com/lukaszj321/otcv8-dev
repo_name: lukaszj321/otcv8-dev
edit_uri: edit/master/docs/
use_directory_urls: true

extra_css:
  - _assets/css/title-fix.css

plugins:
  - search
  - glightbox
  - macros
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  - redirects
  - exclude:
      glob:
        - modules/**/__md_backup_*/**
        - modules/__md_backup_*/**

markdown_extensions:
  - toc:
      permalink: true
      separator: '-'
  - tables
  - fenced_code
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  search:
    exclude:
      - modules/**/__md_backup_*.md

validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    absolute_links: warn
    unrecognized_links: warn
    anchors: warn

# UWAGA: brak sekcji "nav" – MkDocs sam wygeneruje menu na podstawie /docs
