site_name: OTCv8 Dev Docs
site_url: https://lukaszj321.github.io/otcv8-dev/
repo_url: https://github.com/lukaszj321/otcv8-dev

docs_dir: docs

theme:
  name: material
  language: pl
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - content.code.copy

extra_css:
  - _assets/css/overrides.css

plugins:
  - search
  - glightbox
  - macros
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - toc:
      permalink: true
  - attr_list              # pozwala na { #kotwice } w nagłówkach
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tasklist
  - pymdownx.tilde

nav:
  - Strona główna: index.md
  - Architektura:
      - Przegląd frameworka: architektura/framework_overview.md
      - Przegląd klienta:     architektura/client_overview.md
      - src framework:        architektura/src_framework.md
      - src client:           architektura/src_client.md
  - Moduły:
      - modules_core: modules/modules_core.md
      - modules_game_1: modules/modules_game_1.md
      - modules_game_2: modules/modules_game_2.md
      - modules_misc:  modules/modules_misc.md
      - Dokumentacja modułów: modules/modules_Documentation.md
  - API:
      - Lua:            api/lua/luafunctions_client.md
      - Engine UI spec: api/engine/otclient_v_8_specyfikacja_ui.md
      - Presety OTUI:   api/engine/presety_kanoniczne_otui_ts_otc_core.md
      - Addendum:       api/engine/otclient_v_8_addendum_import_z_lua_stringow_auto_strict_goldeny_expanded.md
      - Walidator AST:  api/engine/otclient_v_8_walidator_macierze_ast_i_round_trip_specyfikacja_techniczna.md
  - Dane:
      - Data docs: data/Data_Documentation.md
  - Narzędzia:
      - Tools index: tools/
