site_name: OTCv8 Dev Docs
site_description: Dokumentacja deweloperska OTCv8 (build, API, architektura)
site_url: https://lukaszj321.github.io/otcv8-dev/
repo_url: https://github.com/lukaszj321/otcv8-dev
edit_uri: blob/master/docs/

theme:
  name: material
  language: pl
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
    - toc.integrate

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      fallback_to_build_date: true
  - tags
  - macros

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - _assets/js/mermaid-init.js

nav:
  - Start: index.md
  - Przewodniki:
      - Architektura: guides/architecture.md
  - Build:
      - Windows: build/windows.md
      - Linux: build/linux.md
      - Android: build/android.md
  - Lua: lua/api.md
  - C++: cpp/overview.md
