site_name: OTCv8 Dev Docs
site_description: Dokumentacja deweloperska OTCv8 (build, architektura, Lua/OTUI, realtime)
site_url: https://lukaszj321.github.io/otcv8-dev/
repo_url: https://github.com/lukaszj321/otcv8-dev
edit_uri: blob/master/docs/
theme:
  name: material
  language: pl
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - search.suggest
    - search.highlight
plugins:
  - search
  - with-pdf:
      output_path: downloads/OTCv8-Docs.pdf
      cover_title: "OTCv8 Dev — Dokumentacja"
      cover_subtitle: "Build • Architektura • Lua/OTUI • Realtime"
      toc_level: 3
  - glightbox
  - macros
  - git-revision-date-localized:
      fallback_to_build_date: true
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - tables
  - toc: { permalink: true }
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight: { anchor_linenums: true }
  - pymdownx.tabbed: { alternate_style: true }
extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - _assets/js/mermaid-init.js
nav:
  - Start: index.md
  - Przewodniki:
      - Architektura: guides/architecture.md
      - Moduły (vBot): guides/modules.md
      - Realtime (WebSocket): guides/websocket.md
      - OTUI: ui/otui.md
  - Build:
      - Windows: build/windows.md
      - Linux: build/linux.md
      - Android: build/android.md
  - Lua:
      - API (przykłady): lua/api.md
      - Style guide: lua/style-guide.md
  - C++:
      - Przegląd: cpp/overview.md
  - Narzędzia: tools/index.md
  - Deweloperzy:
      - Contributing: dev/contributing.md
      - Testy: dev/testing.md
      - Release: dev/release.md
      - Security: dev/security.md
      - Troubleshooting: dev/troubleshooting.md
      - FAQ: dev/faq.md
      - Słownik: dev/glossary.md
      - Roadmap: dev/roadmap.md
  - RAG demo: rag/search.html
