site_name: OTCv8 Dev Docs
site_url: https://lukaszj321.github.io/otcv8-dev/
repo_url: https://github.com/lukaszj321/otcv8-dev
edit_uri: ""

docs_dir: docs
use_directory_urls: true

theme:
  name: material
  language: pl
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.action.edit
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

plugins:
  - search
  - glightbox
  - macros
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true

extra_javascript:
  - _assets/js/mermaid-init.js

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.tilde

nav:
  - Start: index.md

  - Architektura:
      - Przegląd klienta: architektura/client_overview.md
      - Przegląd frameworka: architektura/framework_overview.md
      - Źródła (framework): architektura/src_framework.md
      - Źródła (client): architektura/src_client.md

  - Moduły:
      - rdzeń: modules/modules_core.md
      - gameplay 1: modules/modules_game_1.md
      - gameplay 2: modules/modules_game_2.md
      - misc: modules/modules_misc.md
      - dokumentacja modułów: modules_Documentation.md

  - API:
      - Lua:
          - funkcje klienta: api/lua/luafunctions_client.md
          - pełne API (zbiorcze): api/otcv8-full-api.md
      - Engine/UI:
          - specyfikacja UI: api/engine/otclient_v_8_specyfikacja_ui.md
          - presety OTUI/TS (core): api/engine/presety_kanoniczne_otui_ts_otc_core.md
          - addendum (import z Lua, strict/golden): api/engine/otclient_v_8_addendum_import_z_lua_stringow_auto_strict_goldeny_expanded.md
          - walidator AST / round-trip: api/engine/otclient_v_8_walidator_macierze_ast_i_round_trip_specyfikacja_techniczna.md

  - Dane:
      - Data docs: data/Data_Documentation.md

  - Narzędzia:
      - Arrange-Docs.ps1: tools/Arrange-Docs.ps1

  - Pobieralnie:
      - DOCX: downloads/OTCv8-Docs.docx
      - EPUB: downloads/OTCv8-Docs.epub
      - PDF: downloads/OTCv8-Docs.pdf
      - ZIP strony: downloads/site.zip
