%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
  NetworkEquence[05_network:network_sequence] --> Data[Datasets]
  Data --> Page[Index]

click NetworkEquence "./index.html#facet-05_network.network_sequence" "Open network_sequence"
\nclick NetworkSequence "./index.html#facet-05_network.network_sequence" "Open network_sequence"\n