%%{init: { 'theme': 'neutral' }}%%
flowchart LR; sources-->ndk; ndk-->so; data-->assets; assets-->apk; so-->apk;\nclick AndroidBuild "./index.html#facet-14_android.android_build" "Open android_build"\n