%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
  AEtPipeline[06_assets:assets_pipeline] --> Data[Datasets]
  Data --> Page[Index]

click AEtPipeline "./index.html#facet-06_assets.assets_pipeline" "Open assets_pipeline"
click AssetsPipeline "./index.html#facet-06_assets.assets_pipeline" "Open assets_pipeline"