%%{init: {'theme':'dark','themeVariables':{'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}}}%%
graph TD
    subgraph CoreDeclarations
        A[Typedefs]
        B[Enums]
        C[Forward Declarations]
        D[Global Constants]
    end

    E[Other Core Files] --> A & B & C & D
    F[Module Code] --> A & B & C & D
    G[UI Code] --> A & B & C & D
