%%{init: {'theme':'dark','themeVariables':{'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}}}%%
graph TD
    A[Application] -- Requests file operation --> B(FileStream);
    B -- open(filePath, mode) --> C{File on Disk};

    subgraph Operations
        direction LR
        D[read]
        E[write]
        F[seek]
    end

    C -- Interaction --> Operations;
    Operations -- Interaction --> C;
    B -- close() --> G[Release Handle];
