%%{init: {'theme':'dark','themeVariables':{'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}}}%%
classDiagram
    class Application {
        +run()
        +init()
        +terminate()
    }
    class GraphicalApplication {
        +initializeWindow()
        +initializeGraphics()
    }

    Application <|-- GraphicalApplication

    GraphicalApplication o-- Graphics
    GraphicalApplication o-- PlatformWindow
