%%{init: {'theme':'dark','themeVariables':{'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}}}%%
graph TD
    subgraph Application
        A[Module A] -- g_logger.log() --> L;
        B[Module B] -- g_logger.error() --> L;
    end

    subgraph Core
        L(Logger)
    end

    subgraph Sinks
        S1[Console Sink]
        S2[File Sink]
    end
    L --> S1 & S2
