graph TD
    W0["remove (AttackEntry)"]
    W1["name (AttackBotBotPanel)"]
    W2["description (CategoryLabel)"]
    W3["description (SourceLabel)"]
    W4["description (RangeLabel)"]
    W5["PreButton (PreButton)"]
    W6["NexButton (NexButton)"]
    W7["spellName (AttackBotPanel)"]
    W8["AntiRsRange (SettingsPanel)"]
    W9["settings (AttackBotWindow)"]