graph TD
    W0["BotButton (BotButton)"]
    W1["BotSwitch (BotSwitch)"]
    W2["SmallBotSwitch (SmallBotSwitch)"]
    W3["BotLabel (BotLabel)"]
    W4["BotItem (BotItem)"]
    W5["BotTextEdit (BotTextEdit)"]
    W6["BotSeparator (BotSeparator)"]
    W7["botPanelScroll (BotSmallScrollBar)"]
    W8["botPanelScroll (BotPanel)"]
    W9["CaveBotLabel (CaveBotLabel)"]
    W10["SlotComboBoxPopupMenu (SlotComboBoxPopupMenu)"]
    W11["SlotComboBoxPopupMenuButton (SlotComboBoxPopupMenuButton)"]
    W12["SlotComboBox (SlotComboBox)"]