graph TD
    W0["AttackComboBoxPopupMenu (AttackComboBoxPopupMenu)"]
    W1["AttackComboBoxPopupMenuButton (AttackComboBoxPopupMenuButton)"]
    W2["AttackComboBox (AttackComboBox)"]
    W3["FollowComboBoxPopupMenu (FollowComboBoxPopupMenu)"]
    W4["FollowComboBoxPopupMenuButton (FollowComboBoxPopupMenuButton)"]
    W5["FollowComboBox (FollowComboBox)"]
    W6["onCastToggle (ComboTrigger)"]
    W7["commandsToggle (ComboActions)"]
    W8["Triggers (BotServer)"]
    W9["toolsButton (ComboWindow)"]