graph TD
    W0["UturaComboBoxPopupMenu (UturaComboBoxPopupMenu)"]
    W1["UturaComboBoxPopupMenuButton (UturaComboBoxPopupMenuButton)"]
    W2["UturaComboBox (UturaComboBox)"]
    W3["ParalyseSpell (CureConditions)"]
    W4["StopHaste (HoldConditions)"]
    W5["closeButton (ConditionsWindow)"]