graph TD
    W0["scroll (TargetBotCreatureEditorScrollBar)"]
    W1["textEdit (TargetBotCreatureEditorTextEdit)"]
    W2["item (TargetBotCreatureEditorItem)"]
    W3["TargetBotCreatureEditorCheckBox (TargetBotCreatureEditorCheckBox)"]
    W4["cancel (TargetBotCreatureEditorWindow)"]