graph TD
    W0["OfferTableRow (OfferTableRow)"]
    W1["OfferTableColumn (OfferTableColumn)"]
    W2["OfferTableWarningColumn (OfferTableWarningColumn)"]
    W1 --> W2
    W3["OfferTableHeaderRow (OfferTableHeaderRow)"]
    W4["myBuyingTableScrollBar (OfferTableHeaderColumn)"]