graph TD
    W0["CategoryCheckBox (CategoryCheckBox)"]
    W1["scroll (HealScroll)"]
    W2["text (HealItem)"]
    W3["ToolTipLabel (ToolTipLabel)"]
    W4["remove (HealerPlayerEntry)"]
    W5["decrement (PriorityEntry)"]
    W3 --> W5
    W6["vocations (TargetSettings)"]
    W7["botserver (Groups)"]
    W8["sorcerers (Vocations)"]
    W9["list (Priority)"]
    W10["add (AddPlayer)"]
    W11["listScrollBar (PlayerList)"]
    W12["playerList (CustomList)"]
    W13["box (Conditions)"]
    W14["closeButton (FriendHealer)"]