graph TD
    W0["text (DualScrollPanel)"]
    W1["scroll (SingleScrollItemPanel)"]
    W2["scroll2 (DualScrollItemPanel)"]
    W3["item5 (ItemsRow)"]
    W4["items (ItemsPanel)"]
    W5["title (ItemAndButtonPanel)"]
    W6["slot (ItemAndSlotPanel)"]
    W7["slot (TwoItemsAndSlotPanel)"]
    W8["right (DualLabelPanel)"]
    W9["right (LabelAndTextEditPanel)"]
    W10["left (SwitchAndButtonPanel)"]