graph TD
    W0["shopTempButton (LockedPreyPanel)"]
    W1["Star (Star)"]
    W2["NoStar (NoStar)"]
    W3["noBonusIcon (NoCreaturePanel)"]
    W4["lockPreyPrice (ActivePreyPanel)"]
    W5["timeLeft (CreatureAndBonus)"]
    W6["price (BonusReroll)"]
    W7["list (InactivePreyPanel)"]
    W8["choosePreyButton (ChoosePrey)"]
    W9["price (SelectPreyCreature)"]
    W10["price (RerollButton)"]
    W11["text (CardLabel)"]
    W12["text (GoldLabel)"]
    W13["creature (PreyCreatureBox)"]
    W14["openStore (SlotPanel)"]
    W15["time (PreyCreature)"]
    W16["slot3 (PreyTracker)"]