graph TD
    W0["SkillFirstWidget (SkillFirstWidget)"]
    W1["SkillButton (SkillButton)"]
    W2["SmallSkillButton (SmallSkillButton)"]
    W1 --> W2
    W3["SkillNameLabel (SkillNameLabel)"]
    W4["value (SkillValueLabel)"]
    W5["skillId12 (SkillPercentPanel)"]