%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class android_app {
    }
    class android_poll_source {
    }
    class android_app {
    }
    class android_app {
    }
    class android_poll_source {
    }
    class android_poll_source {
    }
