%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class AnimatedText {
        +drawText()
        +setColor()
        +setText()
        +setOffset()
        +setFont()
        +getColor()
        +getOffset()
        +getTimer()
        +merge()
        +asAnimatedText()
        +isAnimatedText()
        +getText()
        #onAppear()
    }
