classDiagram
    class AnimatedText {
        +drawText()
        +setColor()
        +setText()
        +setOffset()
        +setFont()
        +getColor()
        +getOffset()
        +getTimer()
        +merge()
        +asAnimatedText()
        +isAnimatedText()
        +getText()
        #onAppear()
    }