classDiagram
    class Animator {
        +unserialize()
        +serialize()
        +setPhase()
        +getPhase()
        +getPhaseAt()
        +getStartPhase()
        +getAnimationPhases()
        +isAsync()
        +isComplete()
        +getTotalDuration()
        +resetAnimation()
    }