%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class AnimatedTexture {
        +replace()
        +update()
        +isAnimatedTexture()
        #buildHardwareMipmaps()
        #setSmooth()
        #setRepeat()
    }
