%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class Animator {
        +unserialize()
        +serialize()
        +setPhase()
        +getPhase()
        +getPhaseAt()
        +getStartPhase()
        +getAnimationPhases()
        +isAsync()
        +isComplete()
        +getTotalDuration()
        +resetAnimation()
    }
