classDiagram
    class Application {
        +init()
        +deinit()
        +terminate()
        +run()
        +poll()
        +exit()
        +quick_exit()
        +close()
        +restart()
        +restartArgs()
        +setName()
        +setCompactName()
        +setVersion()
        +isRunning()
        +isStopping()
        +isTerminated()
        +getCharset()
        +getBuildCompiler()
        +getBuildDate()
        +getBuildRevision()
        ... (19 more members)
    }