%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class CachedText {
        +draw()
        +wrapText()
        +setFont()
        +setText()
        +setColoredText()
        +setAlign()
        +getTextSize()
        +getText()
        +getFont()
        +getAlign()
        +hasText()
    }
