classDiagram
    class CachedText {
        +draw()
        +wrapText()
        +setFont()
        +setText()
        +setColoredText()
        +setAlign()
        +getTextSize()
        +getText()
        +getFont()
        +getAlign()
        +hasText()
    }