%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class Clock {
        +update()
        +micros()
        +millis()
        +seconds()
        +realMicros()
        +realMillis()
    }
