classDiagram
    class ConfigManager {
        +init()
        +terminate()
        +getSettings()
        +get()
        +create()
        +loadSettings()
        +load()
        +unload()
        +remove()
        #m_settings
    }