%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class ConfigManager {
        +init()
        +terminate()
        +getSettings()
        +get()
        +create()
        +loadSettings()
        +load()
        +unload()
        +remove()
        #m_settings
    }
