classDiagram
    class Config {
        +load()
        +unload()
        +save()
        +clear()
        +setValue()
        +setList()
        +getValue()
        +getList()
        +setNode()
        +mergeNode()
        +getNode()
        +getNodeSize()
        +exists()
        +remove()
        +getFileName()
        +isLoaded()
        +asConfig()
    }