classDiagram
    class Connection {
        +poll()
        +terminate()
        +connect()
        +close()
        +write()
        +read()
        +read_until()
        +read_some()
        +setErrorCallback()
        +getIp()
        +getError()
        +isConnecting()
        +isConnected()
        +getElapsedTicksSinceLastRead()
        +asConnection()
        #internal_connect()
        #internal_write()
        #onResolve()
        #onConnect()
        #onCanWrite()
        ... (18 more members)
    }