classDiagram
    class Container {
        +getItem()
        +getItems()
        +getItemsCount()
        +getSlotPosition()
        +getId()
        +getCapacity()
        +getContainerItem()
        +getName()
        +hasParent()
        +isClosed()
        +isUnlocked()
        +hasPages()
        +getSize()
        +getFirstIndex()
        +findItemById()
        #onOpen()
        #onClose()
        #onAddItem()
        #onAddItems()
        #onUpdateItem()
        ... (1 more members)
    }