classDiagram
    class CoordsBuffer {
        +clear()
        +addTriangle()
        +addRect()
        +addRect()
        +addRect()
        +addQuad()
        +addUpsideDownQuad()
        +addBoudingRect()
        +addRepeatedRects()
        +getVertexCount()
        +getTextureCoordCount()
        +unlock()
        +cache()
        +getTextureRect()
    }