classDiagram
    class Creature {
        +draw()
        +drawOutfit()
        +drawInformation()
        +isInsideOffset()
        +setId()
        +setName()
        +setManaPercent()
        +setHealthPercent()
        +setDirection()
        +setOutfit()
        +setOutfitColor()
        +setLight()
        +setSpeed()
        +setBaseSpeed()
        +setSkull()
        +setShield()
        +setEmblem()
        +setType()
        +setIcon()
        +setSkullTexture()
        ... (175 more members)
    }
    class Npc {
        +isNpc()
    }
    class Monster {
        +isMonster()
    }