classDiagram
    class Spawn {
        +setRadius()
        +getRadius()
        +setCenterPos()
        +getCenterPos()
        +getCreatures()
        +addCreature()
        +removeCreature()
        +clear()
        #load()
        #save()
    }
    class CreatureType {
        +setSpawnTime()
        +getSpawnTime()
        +setName()
        +getName()
        +setOutfit()
        +getOutfit()
        +setDirection()
        +getDirection()
        +setRace()
        +getRace()
        +cast()
    }
    class CreatureManager {
        +clear()
        +clearSpawns()
        +terminate()
        +loadMonsters()
        +loadSingleCreature()
        +loadNpcs()
        +loadCreatureBuffer()
        +loadSpawns()
        +saveSpawns()
        +getSpawns()
        +getSpawn()
        +getSpawnForPlacePos()
        +addSpawn()
        +deleteSpawn()
        +isLoaded()
        +isSpawnLoaded()
        #internalLoadCreatureBuffer()
    }