classDiagram
    class Crypt {
        +base64Encode()
        +base64Decode()
        +xorCrypt()
        +encrypt()
        +decrypt()
        +genUUID()
        +setMachineUUID()
        +getMachineUUID()
        +md5Encode()
        +sha1Encode()
        +sha256Encode()
        +sha512Encode()
        +crc32()
        +rsaGenerateKey()
        +rsaSetPublicKey()
        +rsaSetPrivateKey()
        +rsaCheckKey()
        +rsaEncrypt()
        +rsaDecrypt()
        +rsaGetSize()
        ... (2 more members)
    }