classDiagram
    class UIManager {
    }
    class UIWidget {
    }
    class UITextEdit {
    }
    class UILayout {
    }
    class UIBoxLayout {
    }
    class UIHorizontalLayout {
    }
    class UIVerticalLayout {
    }
    class UIGridLayout {
    }
    class UIAnchor {
    }
    class UIAnchorGroup {
    }
    class UIAnchorLayout {
    }