%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class UIManager {
    }
    class UIWidget {
    }
    class UITextEdit {
    }
    class UILayout {
    }
    class UIBoxLayout {
    }
    class UIHorizontalLayout {
    }
    class UIVerticalLayout {
    }
    class UIGridLayout {
    }
    class UIAnchor {
    }
    class UIAnchorGroup {
    }
    class UIAnchorLayout {
    }
