%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class DepthArray {
        +addDepth()
        +clear()
        +depthCount()
        +count()
        +size()
    }
