%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class EventDispatcher {
        +shutdown()
        +poll()
        +addEventEx()
        +scheduleEventEx()
        +cycleEventEx()
        +isBotSafe()
    }
