classDiagram
    class PHYSFS_File {
        +close()
        +flush()
        +write()
        +read()
        +seek()
        +skip()
        +size()
        +tell()
        +eof()
        +name()
        +getU8()
        +getU16()
        +getU32()
        +getU64()
        +get8()
        +get16()
        +get32()
        +get64()
        +getString()
        +getBinaryTree()
        ... (14 more members)
    }
    class FileStream {
        +close()
        +flush()
        +write()
        +read()
        +seek()
        +skip()
        +size()
        +tell()
        +eof()
        +name()
        +getU8()
        +getU16()
        +getU32()
        +getU64()
        +get8()
        +get16()
        +get32()
        +get64()
        +getString()
        +getBinaryTree()
        ... (14 more members)
    }