classDiagram
    class FontManager {
        +terminate()
        +clearFonts()
        +importFont()
        +fontExists()
        +getFont()
        +getDefaultFont()
        +setDefaultFont()
    }