%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class FontManager {
        +terminate()
        +clearFonts()
        +importFont()
        +fontExists()
        +getFont()
        +getDefaultFont()
        +setDefaultFont()
    }
