classDiagram
    class FrameBuffer {
        +resize()
        +bind()
        +release()
        +draw()
        +draw()
        +draw()
        +setSmooth()
        +getTexture()
        +getSize()
        +isSmooth()
        +getDepthRenderBuffer()
        +hasDepth()
        +readPixels()
        +doScreenshot()
    }