%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class FrameBufferManager {
        +init()
        +terminate()
        +clear()
        +createFrameBuffer()
        #m_temporaryFramebuffer
        #m_drawQueueTemporaryFramebuffer
        #m_framebuffers
    }
