classDiagram
    class FrameBufferManager {
        +init()
        +terminate()
        +clear()
        +createFrameBuffer()
        #m_temporaryFramebuffer
        #m_drawQueueTemporaryFramebuffer
        #m_framebuffers
    }