%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class FrameBuffer {
        +resize()
        +bind()
        +release()
        +draw()
        +draw()
        +draw()
        +setSmooth()
        +getTexture()
        +getSize()
        +isSmooth()
        +getDepthRenderBuffer()
        +hasDepth()
        +readPixels()
        +doScreenshot()
    }
