classDiagram
    class UnjustifiedPoints {
    }
    class Game {
        +init()
        +terminate()
        #processConnectionError()
        #processDisconnect()
        #processPing()
        #processPingBack()
        #processNewPing()
        #processUpdateNeeded()
        #processLoginError()
        #processLoginAdvice()
        #processLoginWait()
        #processLoginToken()
        #processLogin()
        #processPendingGame()
        #processEnterGame()
        #processGameStart()
        #processGameEnd()
        #processDeath()
        #processGMActions()
        #processInventoryChange()
        ... (205 more members)
    }