classDiagram
    class GraphicalApplication {
        +init()
        +deinit()
        +terminate()
        +run()
        +poll()
        +pollGraphics()
        +close()
        +willRepaint()
        +repaint()
        +setMaxFps()
        +getMaxFps()
        +getFps()
        +getGraphicsFps()
        +getProcessingFps()
        +isOnInputEvent()
        +getIteration()
        +m_iteration
        +doScreenshot()
        +scaleUp()
        +scaleDown()
        ... (5 more members)
    }