classDiagram
    class HealthBar {
        +setPath()
        +getPath()
        +setTexture()
        +getTexture()
        +setOffset()
        +getOffset()
        +setBarOffset()
        +getBarOffset()
        +setHeight()
        +getHeight()
    }
    class HealthBars {
        +init()
        +terminate()
        +addHealthBackground()
        +addManaBackground()
        +getHealthBar()
        +getManaBar()
        +getHealthBarPath()
        +getManaBarPath()
        +getHealthBarOffset()
        +getManaBarOffset()
        +getHealthBarOffsetBar()
        +getManaBarOffsetBar()
        +getHealthBarHeight()
        +getManaBarHeight()
    }