classDiagram
    class WebsocketSession {
        +init()
        +terminate()
        +get()
        +post()
        +download()
        +ws()
        +wsSend()
        +wsClose()
        +cancel()
        +m_downloads
        +clearDownloads()
        +getFile()
        +it
        +nullptr
        +setUserAgent()
    }
    class Http {
    }