%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class Image {
        +load()
        +loadPNG()
        +loadPNG()
        +savePNG()
        +blit()
        +paste()
        +upscale()
        +resize()
        +nextMipmap()
        +setPixel()
        +setPixel()
        +setPixel()
        +getPixelCount()
        +getWidth()
        +getHeight()
        +getBpp()
        +fromQRCode()
    }
