classDiagram
    class ItemType {
        +unserialize()
        +setServerId()
        +getServerId()
        +setClientId()
        +getClientId()
        +setCategory()
        +getCategory()
        +setName()
        +getName()
        +setDesc()
        +getDesc()
        +isNull()
        +isWritable()
    }