%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class TileLight {
    }
    class LightView {
        +addLight()
        +addLight()
        +addLight()
        +setFieldBrightness()
        +size()
        +draw()
    }
