classDiagram
    class LocalPlayer {
        +draw()
        +unlockWalk()
        +lockWalk()
        +stopAutoWalk()
        +autoWalk()
        +canWalk()
        +isWalkLocked()
        +turn()
        +setStates()
        +setSkill()
        +setBaseSkill()
        +setHealth()
        +setFreeCapacity()
        +setTotalCapacity()
        +setExperience()
        +setLevel()
        +setMana()
        +setMagicLevel()
        +setBaseMagicLevel()
        +setSoul()
        ... (64 more members)
    }