classDiagram
    class pack_values_into_tuple {
    }
    class pack_values_into_tuple {
    }
    class expand_fun_arguments {
    }
    class expand_fun_arguments {
    }
    class bind_lambda_fun {
    }
    class bind_lambda_fun {
    }