%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class LuaException {
        +generateLuaErrorMessage()
        #m_what
    }
    class LuaBadNumberOfArgumentsException {
    }
    class LuaBadValueCastException {
    }
