%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class push_tuple_internal_luavalue {
    }
    class push_tuple_internal_luavalue {
    }
    class push_tuple_luavalue {
    }
    class push_tuple_luavalue {
    }
