%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class MapView {
        +drawMapBackground()
        +drawMapForeground()
        #onTileUpdate()
        #onMapCenterChange()
        +lockFirstVisibleFloor()
        +unlockFirstVisibleFloor()
        +getLockedFirstVisibleFloor()
        +setMultifloor()
        +isMultifloor()
        +setVisibleDimension()
        +optimizeForSize()
        +getVisibleDimension()
        +getVisibleCenterOffset()
        +getCachedFirstVisibleFloor()
        +getCachedLastVisibleFloor()
        +followCreature()
        +getFollowingCreature()
        +isFollowingCreature()
        +setCameraPosition()
        +getCameraPosition()
        ... (25 more members)
    }
