%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class Missile {
        +draw()
        +setId()
        +setPath()
        +getId()
        +asMissile()
        +isMissile()
        +getSource()
        +getDestination()
    }
