%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class ModuleManager {
        +clear()
        +discoverModules()
        +autoLoadModules()
        +discoverModule()
        +ensureModuleLoaded()
        +unloadModules()
        +reloadModules()
        +getModule()
        +getModules()
        #updateModuleLoadOrder()
    }
