classDiagram
    class Mouse {
        +init()
        +terminate()
        +loadCursors()
        +addCursor()
        +pushCursor()
        +popCursor()
        +isCursorChanged()
        +isPressed()
    }