classDiagram
    class OTMLNode {
        +create()
        +create()
        +tag()
        +size()
        +source()
        +rawValue()
        +isUnique()
        +isNull()
        +hasTag()
        +hasValue()
        +hasChildren()
        +hasChildAt()
        +getIndex()
        +setTag()
        +setValue()
        +setNull()
        +setUnique()
        +setSource()
        +setIndex()
        +lockTag()
        ... (27 more members)
    }