%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class TSize {
        +isNull()
        +toSize()
        +operator
        +length()
        +manhattanLength()
        +distanceFrom()
    }
    class TPoint {
        +isNull()
        +toSize()
        +operator
        +length()
        +manhattanLength()
        +distanceFrom()
    }
