classDiagram
    class TSize {
        +isNull()
        +toSize()
        +operator
        +length()
        +manhattanLength()
        +distanceFrom()
    }
    class TPoint {
        +isNull()
        +toSize()
        +operator
        +length()
        +manhattanLength()
        +distanceFrom()
    }