%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class Position {
        +translatedToDirection()
        +pos
        +pos
        +translatedToReverseDirection()
        +pos
        +pos
        +translatedToDirections()
        +lastPos
        +positions
        +positions
        +positions
        +getAngleFromPositions()
        +dx
        +dy
        +angle
        +angle
        +getAngleFromPosition()
        +getAngleFromPositions()
        +angle
        +if()
        ... (37 more members)
    }
    class PositionHasher {
    }
