classDiagram
    class ResourceManager {
        +init()
        +terminate()
        +launchCorrect()
        +setupWriteDir()
        +setup()
        +getCompactName()
        +loadDataFromSelf()
        +fileExists()
        +directoryExists()
        +readFileStream()
        +readFileContents()
        +readFileContentsSafe()
        +isFileEncryptedOrCompressed()
        +writeFileBuffer()
        +writeFileContents()
        +writeFileStream()
        +openFile()
        +appendFile()
        +createFile()
        +deleteFile()
        ... (28 more members)
    }