%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class ScheduledEvent {
        +execute()
        +nextCycle()
        +ticks()
        +remainingTicks()
        +delay()
        +cyclesExecuted()
        +maxCycles()
    }
    class lessScheduledEvent {
    }
