classDiagram
    class ShaderManager {
        +init()
        +terminate()
        +createShader()
        +createOutfitShader()
        +createShader()
        +addTexture()
        +getShader()
    }