%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class ShaderManager {
        +init()
        +terminate()
        +createShader()
        +createOutfitShader()
        +createShader()
        +addTexture()
        +getShader()
    }
