%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class Shader {
        +compileSourceCode()
        +compileSourceFile()
        +log()
        +getShaderId()
        +getShaderType()
    }
