%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class TSize {
        +toPoint()
        +isNull()
        +isEmpty()
        +isValid()
        +width()
        +height()
        +resize()
        +setWidth()
        +setHeight()
        +operator
        +expandedTo()
        +boundedTo()
        +scale()
        +useHeight
        +rw
        +scale()
        +ratio()
        +area()
    }
