classDiagram
    class SoundSource {
        +play()
        +stop()
        +isBuffering()
        +isPlaying()
        +setName()
        +setLooping()
        +setRelative()
        +setReferenceDistance()
        +setGain()
        +setPitch()
        +setPosition()
        +setVelocity()
        +setFading()
        +getName()
        +getChannel()
        +getGain()
        #setBuffer()
        #setChannel()
        #update()
        #m_sourceId
        ... (8 more members)
    }