%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class SpriteManager {
        +terminate()
        +loadSpr()
        +unload()
        +saveSpr()
        +saveSpr64()
        +encryptSprites()
        +dumpSprites()
        +getSignature()
        +getSpritesCount()
        +getSpriteImage()
        +isLoaded()
        +spriteSize()
        +getOffsetFactor()
        +isHdMod()
    }
