classDiagram
    class Stat {
    }
    class StatsData {
    }
    class UIWidget {
        +add()
        +get()
        +clear()
        +clearAll()
        +getSlow()
        +clearSlow()
        +types()
        +getSleepTime()
        +m_sleepTime
        +resetSleepTime()
        +m_sleepTime
        +addWidget()
        +removeWidget()
        +getWidgetsInfo()
        +addTexture()
        +removeTexture()
        +addThing()
        +removeThing()
        +addCreature()
        +removeCreature()
    }
    class Stats {
    }
    class AutoStat {
    }