%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class StreamSoundSource {
        +play()
        +stop()
        +isPlaying()
        +setSoundFile()
        +downMix()
        +update()
    }
