%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class TextureManager {
        +init()
        +terminate()
        +clearCache()
        +reload()
        +preload()
        +getTexture()
        +loadTexture()
    }
