classDiagram
    class Texture {
        +replace()
        +resize()
        +update()
        +setUpsideDown()
        +setSmooth()
        +setRepeat()
        +buildHardwareMipmaps()
        +setTime()
        +setCanCache()
        +getId()
        +getUniqueId()
        +getTime()
        +getWidth()
        +getHeight()
        +isEmpty()
        +hasRepeat()
        +hasMipmaps()
        +canCache()
        +isAnimatedTexture()
        #uploadPixels()
        ... (18 more members)
    }