%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class TextRenderCache {
    }
    class TextRender {
        +init()
        +terminate()
        +poll()
        +addText()
        +drawText()
        +drawText()
        +drawColoredText()
    }
