classDiagram
    class ThingTypeManager {
        +init()
        +terminate()
        +check()
        +loadDat()
        +loadOtml()
        +loadOtb()
        +loadXml()
        +parseItemType()
        +saveDat()
        +dumpTextures()
        +replaceTextures()
        +addItemType()
        +findItemTypesByName()
        +findItemTypesByString()
        +getMarketCategories()
        +m_marketCategories
        +findThingTypeByAttr()
        +findItemTypeByCategory()
        +getDatSignature()
        +getOtbMajorVersion()
        ... (7 more members)
    }