classDiagram
    class Thing {
        +draw()
        +setId()
        +setPosition()
        +getId()
        +getPosition()
        +getStackPriority()
        +getParentContainer()
        +getStackPos()
        +setMarked()
        +updatedMarkedColor()
        +isItem()
        +isEffect()
        +isMissile()
        +isCreature()
        +isNpc()
        +isMonster()
        +isPlayer()
        +isLocalPlayer()
        +isAnimatedText()
        +isStaticText()
        ... (73 more members)
    }