classDiagram
    class ThingsType {
        +load()
        +unload()
        +parseThingType()
        +getSignature()
        +isLoaded()
        +getFirstItemId()
        +getMaxItemid()
        +isValidItemId()
    }