%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class TiXmlString {
    }
    class Rep {
    }
    class TiXmlOutStream {
    }
