classDiagram
    class Town {
        +setId()
        +setName()
        +setPos()
        +getId()
        +getName()
        +getPos()
    }
    class TownManager {
        +addTown()
        +removeTown()
        +sort()
        +getTowns()
        +clear()
        #findTown()
    }