classDiagram
    class UIBoxLayout {
        +applyStyle()
        +addWidget()
        +removeWidget()
        +setSpacing()
        +setFitChildren()
        +isUIBoxLayout()
        #m_fitChildren
        #m_spacing
    }