classDiagram
    class UICreature {
        +drawSelf()
        +setCreature()
        +setFixedCreatureSize()
        +setOutfit()
        +getCreature()
        +getOutfit()
        +isFixedCreatureSize()
        +setAutoRotating()
        +setDirection()
        +getDirection()
        +setScale()
        +getScale()
        +setAnimate()
        +isAnimating()
        +setCenter()
        +setOldScaling()
        #onStyleApply()
        #onGeometryChange()
        #m_creature
        #m_autoRotating
        ... (4 more members)
    }