classDiagram
    class UIGridLayout {
        +applyStyle()
        +removeWidget()
        +addWidget()
        +setCellSize()
        +setCellWidth()
        +setCellHeight()
        +setCellSpacing()
        +setNumColumns()
        +setNumLines()
        +setAutoSpacing()
        +setFitChildren()
        +setFlow()
        +getCellSize()
        +getCellSpacing()
        +getNumColumns()
        +getNumLines()
        +isUIGridLayout()
        #internalUpdate()
    }