classDiagram
    class UIHorizontalLayout {
        +applyStyle()
        +setAlignRight()
        +isUIHorizontalLayout()
        #internalUpdate()
        #m_alignChidren
        #m_alignRight
    }