%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class UIHorizontalLayout {
        +applyStyle()
        +setAlignRight()
        +isUIHorizontalLayout()
        #internalUpdate()
        #m_alignChidren
        #m_alignRight
    }
