classDiagram
    class UIMinimap {
        +drawSelf()
        +zoomIn()
        +zoomOut()
        +setZoom()
        +setMinZoom()
        +setMaxZoom()
        +setCameraPosition()
        +floorUp()
        +floorDown()
        +getTilePoint()
        +getTileRect()
        +getTilePosition()
        +getCameraPosition()
        +getMinZoom()
        +getMaxZoom()
        +getZoom()
        +getScale()
        +anchorPosition()
        +fillPosition()
        +centerInPosition()
        ... (3 more members)
    }