classDiagram
    class UISprite {
        +drawSelf()
        +setSpriteId()
        +getSpriteId()
        +clearSprite()
        +setSpriteColor()
        +isSpriteVisible()
        +setSpriteVisible()
        +hasSprite()
        #onStyleApply()
        #m_sprite
        #m_spriteId
        #m_spriteColor
        #m_spriteVisible
    }