%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
classDiagram
    class UIVerticalLayout {
        +applyStyle()
        +setAlignBottom()
        +isAlignBottom()
        +isUIVerticalLayout()
        #internalUpdate()
        #m_alignBottom
    }
