classDiagram
    class EdgeGroup {
    }
    class UIWidget {
        +draw()
        #drawSelf()
        #drawChildren()
        #m_id
        #m_source
        #m_rect
        #m_virtualOffset
        #m_autoDraw
        #m_enabled
        #m_visible
        #m_focusable
        #m_fixedSize
        #m_phantom
        #m_draggable
        #m_destroyed
        #m_clipping
        #m_layout
        #m_parent
        #m_parentId
        #m_children
        ... (374 more members)
    }