classDiagram
    class X11Window {
        +init()
        +terminate()
        +move()
        +resize()
        +show()
        +hide()
        +minimize()
        +maximize()
        +poll()
        +swapBuffers()
        +showMouse()
        +hideMouse()
        +setMouseCursor()
        +restoreMouseCursor()
        +setTitle()
        +setMinimumSize()
        +setFullscreen()
        +setVerticalSync()
        +setIcon()
        +setClipboardText()
        ... (5 more members)
    }