%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
  game_interface --> game_skills
  game_interface --> game_inventory
  game_interface --> game_console
  game_skills --> game_stats
