%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
  LoggingFlow[09_logging:logging_flow] --> Data[Datasets]
  Data --> Page[Index]

click LoggingFlow "./index.html#facet-09_logging.logging_flow" "Open logging_flow"
