#!/usr/bin/env python3
"""
High-level orchestrator script that runs the maintenance steps to fix Sphinx docs,
create placeholders for missing includes, dedupe anchors, and optionally clean up
.md files and scripts/tools directories.

Usage:
  # Dry run (no changes):
  python3 fix_sphinx_and_cleanup.py --dry-run

  # Apply changes (will create backups for modified files and create placeholders):
  python3 fix_sphinx_and_cleanup.py --apply

This script invokes the helper scripts in the same folder. It does NOT push to git.
Run locally in the repo root.
"""
import argparse
import subprocess
import sys
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent

HELPERS = [
    'find_and_stub_missing_docs.py',
    'detect_duplicate_anchors.py',
    'dedupe_anchors.py',
    'cleanup_scripts_tools.py'
]

parser = argparse.ArgumentParser()
parser.add_argument('--apply', action='store_true', help='Apply changes (create backups and write files)')
parser.add_argument('--report', action='store_true', help='Generate report only')
args = parser.parse_args()

mode = '--apply' if args.apply else ''

print('Running maintenance scripts (dry-run by default).')
for helper in HELPERS:
    path = SCRIPTS_DIR / helper
    if not path.exists():
        print('Missing helper:', helper)
        continue
    cmd = [sys.executable, str(path)]
    if args.apply:
        cmd.append('--apply')
    print('\n>>> Running:', ' '.join(cmd))
    subprocess.run(cmd, check=False)

print('\nAll helper scripts executed.\n')
if args.report:
    # generate a simple report placeholder
    rpt = Path('docs/reports/sphinx_fix_report.md')
    rpt.write_text('# Sphinx Fix Report\n\n(Report will be generated by review of outputs from helper scripts.)\n')
    print('Report written to', rpt)
