%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
    W0["buttonOk (AmountWindow)"]
\nclick Amountwindow "./index.html#facet-04_ui.amountwindow" "Open amountwindow"\n