graph TD
    W0["cooldown (BossCreaturePanel)"]
    W1["clear (SearchPanel)"]
    W2["drops (TrackerItem)"]
    W3["value (DualLabel)"]
    W4["healing (MemberWidget)"]
    W5["remove (AnalyzerPriceLabel)"]
    W6["AnalyzerListPanel (AnalyzerListPanel)"]
    W7["ListLabel (ListLabel)"]
    W8["List (AnalyzerItemsPanel)"]
    W9["count (AnalyzerLootItem)"]
    W10["AnalyzerGraph (AnalyzerGraph)"]
    W11["AnalyzerProgressBar (AnalyzerProgressBar)"]
    W12["AnalyzerButton (AnalyzerButton)"]
    W13["ResetSession (MainAnalyzerWindow)"]
    W14["HuntingAnalyzerWindow (HuntingAnalyzer)"]
    W15["LootAnalyzerWindow (LootAnalyzer)"]
    W16["SupplyAnalyzerWindow (SupplyAnalyzer)"]
    W17["ImpactAnalyzerWindow (ImpactAnalyzer)"]
    W18["XPAnalyzerWindow (XPAnalyzer)"]
    W19["PartyAnalyzerWindow (PartyAnalyzerWindow)"]
    W20["DropTracker (DropTracker)"]
    W21["CaveBotStats (CaveBotStats)"]
    W22["search (BossTracker)"]
    W23["closeButton (FeaturesWindow)"]