graph TD
    W0["BattleIcon (BattleIcon)"]
    W1["BattlePlayers (BattlePlayers)"]
    W0 --> W1
    W2["BattleNPCs (BattleNPCs)"]
    W0 --> W2
    W3["BattleMonsters (BattleMonsters)"]
    W0 --> W3
    W4["BattleSkulls (BattleSkulls)"]
    W0 --> W4
    W5["battlePanel (BattleParty)"]
    W0 --> W5