%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
    W0["cancelButton (BugReportWindow)"]
\nclick Bugreport "./index.html#facet-04_ui.bugreport" "Open bugreport"\n