%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
    W0["buttonCancel (CharacterWidget)"]
click Characterlist "./index.html#facet-04_ui.characterlist" "Open characterlist"