%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
    W0["remove (BotConfig)"]
\nclick Config "./index.html#facet-04_ui.config" "Open config"\n