%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
    W0["scroll (TargetBotCreatureEditorScrollBar)"]
    W1["textEdit (TargetBotCreatureEditorTextEdit)"]
    W2["item (TargetBotCreatureEditorItem)"]
    W3["TargetBotCreatureEditorCheckBox (TargetBotCreatureEditorCheckBox)"]
    W4["cancel (TargetBotCreatureEditorWindow)"]
\nclick CreatureEditor "./index.html#facet-04_ui.creature_editor" "Open creature_editor"\n