%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
    W0["autoRecording (CaveBotEditorButton)"]
    W1["autoRecording (CaveBotEditorPanel)"]
click Editor "./index.html#facet-04_ui.editor" "Open editor"