%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
    W0["buttonCancel (IconButton)"]
\nclick Editvip "./index.html#facet-04_ui.editvip" "Open editvip"\n