graph TD
    W0["SlotBotItem (SlotBotItem)"]
    W1["remove (BossLabel)"]
    W2["ConditionBoxPopupMenu (ConditionBoxPopupMenu)"]
    W3["ConditionBoxPopupMenuButton (ConditionBoxPopupMenuButton)"]
    W4["ConditionBox (ConditionBox)"]
    W5["PreButton (PreButton)"]
    W6["NexButton (NexButton)"]
    W7["text (CondidionLabel)"]
    W8["visible (Rule)"]
    W9["text (ConditionPanel)"]
    W10["down (ListPanel)"]
    W11["add (InputPanel)"]
    W12["default (EQPanel)"]
    W13["profileName (Profile)"]
    W14["add (BossList)"]
    W15["bossList (EquipWindow)"]