graph TD
    W0["SettingCheckBox (SettingCheckBox)"]
    W1["SpellSourceBoxPopupMenu (SpellSourceBoxPopupMenu)"]
    W2["SpellSourceBoxPopupMenuButton (SpellSourceBoxPopupMenuButton)"]
    W3["SpellSourceBox (SpellSourceBox)"]
    W4["SpellConditionBoxPopupMenu (SpellConditionBoxPopupMenu)"]
    W5["SpellConditionBoxPopupMenuButton (SpellConditionBoxPopupMenuButton)"]
    W6["SpellConditionBox (SpellConditionBox)"]
    W7["remove (SpellEntry)"]
    W8["remove (ItemEntry)"]
    W9["MoveDown (SpellHealing)"]
    W10["MoveDown (ItemHealing)"]
    W11["items (HealerPanel)"]
    W12["ResetSettings (HealBotSettingsPanel)"]
    W13["settingsButton (HealWindow)"]