%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
    W0["cancelButton (ItemSelectorWindow)"]
click Itemselector "./index.html#facet-04_ui.itemselector" "Open itemselector"