%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
    W0["DetailsTableRow (DetailsTableRow)"]
    W1["detailsTableScrollBar (DetailsTableColumn)"]
\nclick Itemdetails "./index.html#facet-04_ui.itemdetails" "Open itemdetails"\n