graph TD
    W0["MarketComboBoxPopupMenuButton (MarketComboBoxPopupMenuButton)"]
    W1["MarketComboBoxPopupMenuSeparator (MarketComboBoxPopupMenuSeparator)"]
    W2["MarketComboBoxPopupMenu (MarketComboBoxPopupMenu)"]
    W3["MarketComboBox (MarketComboBox)"]