graph TD
    W0["MarketTabBar (MarketTabBar)"]
    W1["MarketTabBarPanel (MarketTabBarPanel)"]
    W2["MarketTabBarButton (MarketTabBarButton)"]
    W3["MarketRightTabBar (MarketRightTabBar)"]
    W4["MarketRightTabBarPanel (MarketRightTabBarPanel)"]
    W5["MarketRightTabBarButton (MarketRightTabBarButton)"]