%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
    W0["MarketButtonBox (MarketButtonBox)"]
\nclick Marketbuttons "./index.html#facet-04_ui.marketbuttons" "Open marketbuttons"\n