%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
    W0["MarketTabBar (MarketTabBar)"]
    W1["MarketTabBarPanel (MarketTabBarPanel)"]
    W2["MarketTabBarButton (MarketTabBarButton)"]
    W3["MarketRightTabBar (MarketRightTabBar)"]
    W4["MarketRightTabBarPanel (MarketRightTabBarPanel)"]
    W5["MarketRightTabBarButton (MarketRightTabBarButton)"]
click Markettabs "./index.html#facet-04_ui.markettabs" "Open markettabs"