graph TD
    W0["ChoiceListLabel (ChoiceListLabel)"]
    W1["choiceList (ChoiceList)"]
    W2["choiceScrollBar (ChoiceScrollBar)"]
    W3["ModalButton (ModalButton)"]
    W4["buttonsPanel (ModalDialog)"]