%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
    W0["NPCOfferLabel (NPCOfferLabel)"]
    W1["tradeButton (NPCItemBox)"]
click Npctrade "./index.html#facet-04_ui.npctrade" "Open npctrade"