%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
    W0["OptionCheckBox (OptionCheckBox)"]
    W1["OptionScrollbar (OptionScrollbar)"]
    W2["optionsTabContent (OptionPanel)"]
\nclick Options "./index.html#facet-04_ui.options" "Open options"\n