%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
    W0["closeButton (PushMaxWindow)"]
click Pushmax "./index.html#facet-04_ui.pushmax" "Open pushmax"