graph TD
    W0["description (QuestTrackerLabel)"]
    W1["QuestLabel (QuestLabel)"]
    W2["questListScrollBar (QuestLog)"]
    W3["missionDescription (MissionLog)"]
    W4["trackerButton (QuestLogWindow)"]
    W5["list (QuestTracker)"]