graph TD
    W0["name (ShopCategory)"]
    W1["item (ShopCategoryItem)"]
    W0 --> W1
    W2["creature (ShopCategoryCreature)"]
    W0 --> W2
    W3["image (ShopCategoryImage)"]
    W0 --> W3
    W4["buyButton (ShopOffer)"]
    W5["item (ShopOfferItem)"]
    W4 --> W5
    W6["creature (ShopOfferCreature)"]
    W4 --> W6
    W7["buttonCancel (ShopOfferImage)"]
    W4 --> W7