%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
    W0["cooldown (SideActionButton)"]
    W1["image (TopSliders)"]
    W2["nextPanel (BottomSliders)"]
\nclick Sideactionbar "./index.html#facet-04_ui.sideactionbar" "Open sideactionbar"\n