%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
    W0["statusLabel (TextMessageLabel)"]
\nclick Textmessage "./index.html#facet-04_ui.textmessage" "Open textmessage"\n