%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
    W0["rejectButton (TradeWindow)"]
\nclick Tradewindow "./index.html#facet-04_ui.tradewindow" "Open tradewindow"\n