%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
  WidgetHierarchy[04_ui:widgets_hierarchy] --> Data[Datasets]
  Data --> Page[Index]

click WidgetHierarchy "./index.html#facet-04_ui.widgets_hierarchy" "Open widgets_hierarchy"
