%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
flowchart LR
  A[Dataset]:::d --> B[Facet Anchor]:::f
  B --> C[Chapter]:::c
classDef d stroke-width:2,stroke-dasharray: 5 5
classDef f fill:#222,stroke:#999
classDef c fill:#333,stroke:#aaa
