%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
  EventOverview[05_events:events_overview] --> Data[Datasets]
  Data --> Page[Index]

click EventOverview "./index.html#facet-05_events.events_overview" "Open events_overview"
\nclick EventsOverview "./index.html#facet-05_events.events_overview" "Open events_overview"\n