%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
    Home[Home Screen] --> Inv[Inventory]
    Home --> Map
    Inv --> Inspect
    click Home "./index.html#facet-13_layouts.layouts" "Open layouts dataset"
\nclick LayoutsTopology "./index.html#facet-13_layouts.layouts_topology" "Open layouts_topology"\n