%%{init: { 'theme': 'neutral' }}%%
graph TD; data-->images; data-->styles; layouts-->images; layouts-->styles;\nclick LayoutsOverview "./index.html#facet-13_layouts.layouts_overview" "Open layouts_overview"