%%{init: { 'theme': 'neutral' }}%%
sequenceDiagram; UI->>Resolver: path; alt exists; Resolver-->>UI: layout; else not; Resolver-->>UI: data; end;\nclick OverrideResolution "./index.html#facet-13_layouts.override_resolution" "Open override_resolution"\n