%%{init: {'theme':'dark','securityLevel':'loose','themeVariables':{'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}}}%%
graph TD
    A[Layouts] --> B[Components]
    A --> C[Datasets]
    A --> D[Diagrams]
