%%{init: { 'theme': 'neutral' }}%%
sequenceDiagram
    participant UI
    participant Resolver
    UI->>Resolver: path
    alt exists
        Resolver-->>UI: layout
    else not
        Resolver-->>UI: data
   end