%%{init: { 'theme': 'neutral' }}%%
flowchart LR
  OTUI[OTUI props]-->IMG(images.csv)
  OTUI-->FNT(fonts.csv)
  OTUI-->STY(styles.csv)
  IMG-->USE(ui_asset_usage.csv)
  FNT-->USE
  STY-->USE
click AssetToUi "./index.html#facet-11_data.asset_to_ui" "Open asset_to_ui"