classDiagram
    class BitmapFont {
        +load()
        +drawText()
        +drawText()
        +drawColoredText()
        +calculateDrawTextCoords()
        +align
        +calculateTextRectSize()
        +wrapText()
        +getId()
        +getName()
        +getGlyphHeight()
        +getYOffset()
        +getGlyphSpacing()
    }