classDiagram
    class Color {
        +a()
        +b()
        +g()
        +r()
        +aF()
        +bF()
        +gF()
        +rF()
        +setRed()
        +setGreen()
        +setBlue()
        +setAlpha()
        +setRed()
        +setGreen()
        +setBlue()
        +setAlpha()
        +setRGBA()
        +setRGBA()
        +opacity()
        +Color()
        ... (14 more members)
    }