classDiagram
    class CombinedSoundSource {
        +addSource()
        +getSources()
        +play()
        +stop()
        +isBuffering()
        +isPlaying()
        +setLooping()
        +setRelative()
        +setReferenceDistance()
        +setGain()
        +setPitch()
        +setPosition()
        +setVelocity()
        +setFading()
        #update()
    }