classDiagram
    class DrawQueue {
    }
    class DrawQueueItem {
    }
    class DrawQueueItem {
    }
    class DrawQueueItemTexturedRect {
    }
    class DrawQueueItemTextureCoords {
    }
    class DrawQueueItemColoredTextureCoords {
    }
    class DrawQueueItemImageWithShader {
    }
    class DrawQueueItemFilledRect {
    }
    class DrawQueueItemClearRect {
    }
    class DrawQueueItemFillCoords {
    }
    class DrawQueueItemText {
    }
    class DrawQueueItemTextColored {
    }
    class DrawQueueItemLine {
    }
    class DrawQueueCondition {
    }
    class DrawQueueConditionClip {
    }
    class DrawQueueConditionRotation {
    }
    class DrawQueueConditionMark {
    }
    class DrawQueue {
    }