classDiagram
    class Event {
        +execute()
        +cancel()
        +isCanceled()
        +isExecuted()
        +isBotSafe()
        #m_function
        #m_callback
        #m_canceled
        #m_executed
        #m_botSafe
    }