classDiagram
    class Painter {
        +init()
        +terminate()
        +resize()
        +checkDepthSupport()
        +getMaxTextureSize()
        +getVendor()
        +getRenderer()
        +getVersion()
        +getExtensions()
        +ok()
        +checkForError()
    }
    class Graphics {
        +init()
        +terminate()
        +resize()
        +checkDepthSupport()
        +getMaxTextureSize()
        +getVendor()
        +getRenderer()
        +getVersion()
        +getExtensions()
        +ok()
        +checkForError()
    }