classDiagram
    class House {
        +setTile()
        +getTile()
        +setName()
        +getName()
        +setId()
        +getId()
        +setTownId()
        +getTownId()
        +setSize()
        +getSize()
        +setRent()
        +getRent()
        +setEntry()
        +getEntry()
        +addDoor()
        +removeDoor()
        +removeDoorById()
        #load()
        #save()
    }
    class HouseManager {
    }