classDiagram
    class InputMessage {
        +setBuffer()
        +getBuffer()
        +getBodyBuffer()
        +skipBytes()
        +setReadPos()
        +getU8()
        +getU16()
        +getU32()
        +getU64()
        +getString()
        +getDouble()
        +peekU8()
        +peekU16()
        +peekU32()
        +peekU64()
        +decryptRsa()
        +getHeaderPos()
        +getHeaderSize()
        +getReadSize()
        +getReadPos()
        ... (10 more members)
    }