classDiagram
    class Item {
        +create()
        +createFromOtb()
        +draw()
        +draw()
        +setId()
        +setOtbId()
        +setCountOrSubType()
        +setCount()
        +setSubType()
        +setColor()
        +setTooltip()
        +setQuickLootFlags()
        +setShader()
        +getCountOrSubType()
        +getSubType()
        +getCount()
        +getId()
        +getClientId()
        +getServerId()
        +getName()
        ... (42 more members)
    }