classDiagram
    class LogMessage {
    }
    class Logger {
        +log()
        +logFunc()
        +debug()
        +info()
        +warning()
        +error()
        +fatal()
        +fireOldMessages()
        +setLogFile()
        +setOnLog()
        +getLastLog()
        +m_lastLog
        +setTestingMode()
    }