classDiagram
    class lua_State {
        +init()
        +terminate()
        +registerFunctions()
        +registerSingletonClass()
        +registerClass()
        +registerClass()
        +registerClassStaticFunction()
        +registerClassMemberFunction()
        +bindSingletonFunction()
        +bindSingletonFunction()
        +bindSingletonFunction()
        +bindClassStaticFunction()
        +bindClassStaticFunction()
        +bindClassMemberFunction()
        +bindClassMemberFunction()
        +bindClassMemberField()
        +bindClassMemberField()
        +bindClassMemberGetField()
        +bindClassMemberGetField()
        +bindClassMemberSetField()
        ... (105 more members)
    }
    class LuaInterface {
        +init()
        +terminate()
        +registerFunctions()
        +registerSingletonClass()
        +registerClass()
        +registerClass()
        +registerClassStaticFunction()
        +registerClassMemberFunction()
        +bindSingletonFunction()
        +bindSingletonFunction()
        +bindSingletonFunction()
        +bindClassStaticFunction()
        +bindClassStaticFunction()
        +bindClassMemberFunction()
        +bindClassMemberFunction()
        +bindClassMemberField()
        +bindClassMemberField()
        +bindClassMemberGetField()
        +bindClassMemberGetField()
        +bindClassMemberSetField()
        ... (105 more members)
    }