classDiagram
    class LuaObject {
        +connectLuaField()
        +luaCallLuaField()
        +callLuaField()
        +callLuaField()
        +hasLuaField()
        +setLuaField()
        +getLuaField()
        +releaseLuaFieldsTable()
        +luaSetField()
        +luaGetField()
        +luaGetMetatable()
        +luaGetFieldsTable()
        +getUseCount()
        +getClassName()
        +asLuaObject()
        +operator
    }
    class connect_lambda {
    }
    class connect_lambda {
    }