classDiagram
    class TileBlock {
    }
    class AwareRange {
    }
    class PathFindResult {
    }
    class Node {
    }
    class Map {
        +init()
        +terminate()
        +addMapView()
        +removeMapView()
        +notificateTileUpdate()
        +requestVisibleTilesCacheUpdate()
        +loadOtcm()
        +saveOtcm()
        +loadOtbm()
        +saveOtbm()
        +setHouseFile()
        +setSpawnFile()
        +setDescription()
        +clearDescriptions()
        +setWidth()
        +setHeight()
        +getHouseFile()
        +getSpawnFile()
        +getSize()
        +getDescriptions()
        ... (58 more members)
    }