classDiagram
    class PlatformWindow {
        +init()
        +terminate()
        +move()
        +resize()
        +show()
        +hide()
        +minimize()
        +maximize()
        +poll()
        +swapBuffers()
        +showMouse()
        +hideMouse()
        +displayFatalError()
        +loadMouseCursor()
        +setMouseCursor()
        +restoreMouseCursor()
        +setTitle()
        +setMinimumSize()
        +setFullscreen()
        +setVerticalSync()
        ... (58 more members)
    }