classDiagram
    class Platform {
        +processArgs()
        +spawnProcess()
        +getProcessId()
        +isProcessRunning()
        +killProcess()
        +getTempPath()
        +getCurrentDir()
        +copyFile()
        +fileExists()
        +removeFile()
        +getFileModificationTime()
        +openUrl()
        +openDir()
        +getCPUName()
        +getTotalSystemMemory()
        +getMemoryUsage()
        +getOSName()
        +traceback()
        +getMacAddresses()
        +getUserName()
        ... (3 more members)
    }