classDiagram
    class ProtocolGame {
        +login()
        +send()
        +sendExtendedOpcode()
        +sendLoginPacket()
        +sendWorldName()
        +sendEnterGame()
        +sendLogout()
        +sendPing()
        +sendPingBack()
        +sendNewPing()
        +sendAutoWalk()
        +sendWalkNorth()
        +sendWalkEast()
        +sendWalkSouth()
        +sendWalkWest()
        +sendStop()
        +sendWalkNorthEast()
        +sendWalkSouthEast()
        +sendWalkSouthWest()
        +sendWalkNorthWest()
        ... (97 more members)
    }