classDiagram
    class Protocol {
        +connect()
        +disconnect()
        +setRecorder()
        +playRecord()
        +isConnected()
        +isConnecting()
        +getElapsedTicksSinceLastRead()
        +getConnection()
        +setConnection()
        +generateXteaKey()
        +setXteaKey()
        +getXteaKey()
        +enableXteaEncryption()
        +enableChecksum()
        +enabledSequencedPackets()
        +enableBigPackets()
        +enableCompression()
        +send()
        +recv()
        +asProtocol()
        ... (11 more members)
    }