classDiagram
    class TPoint {
        +isNull()
        +isEmpty()
        +isValid()
        +left()
        +top()
        +right()
        +bottom()
        +horizontalCenter()
        +verticalCenter()
        +x()
        +y()
        +topLeft()
        +bottomRight()
        +topRight()
        +bottomLeft()
        +topCenter()
        +bottomCenter()
        +centerLeft()
        +centerRight()
        +center()
        ... (102 more members)
    }
    class TSize {
        +isNull()
        +isEmpty()
        +isValid()
        +left()
        +top()
        +right()
        +bottom()
        +horizontalCenter()
        +verticalCenter()
        +x()
        +y()
        +topLeft()
        +bottomRight()
        +topRight()
        +bottomLeft()
        +topCenter()
        +bottomCenter()
        +centerLeft()
        +centerRight()
        +center()
        ... (102 more members)
    }
    class TRect {
        +isNull()
        +isEmpty()
        +isValid()
        +left()
        +top()
        +right()
        +bottom()
        +horizontalCenter()
        +verticalCenter()
        +x()
        +y()
        +topLeft()
        +bottomRight()
        +topRight()
        +bottomLeft()
        +topCenter()
        +bottomCenter()
        +centerLeft()
        +centerRight()
        +center()
        ... (102 more members)
    }