classDiagram
    class ScheduledEvent {
        +execute()
        +nextCycle()
        +ticks()
        +remainingTicks()
        +delay()
        +cyclesExecuted()
        +maxCycles()
    }
    class lessScheduledEvent {
    }