classDiagram
    class TSize {
        +toPoint()
        +isNull()
        +isEmpty()
        +isValid()
        +width()
        +height()
        +resize()
        +setWidth()
        +setHeight()
        +operator
        +expandedTo()
        +boundedTo()
        +scale()
        +useHeight
        +rw
        +scale()
        +ratio()
        +area()
    }