classDiagram
    class SoundChannel {
        +play()
        +stop()
        +enqueue()
        +enable()
        +disable()
        +setGain()
        +getGain()
        +setEnabled()
        +isEnabled()
        +getId()
        #update()
    }
    class QueueEntry {
    }