classDiagram
    class SpriteManager {
        +terminate()
        +loadSpr()
        +unload()
        +saveSpr()
        +saveSpr64()
        +encryptSprites()
        +dumpSprites()
        +getSignature()
        +getSpritesCount()
        +getSpriteImage()
        +isLoaded()
        +spriteSize()
        +getOffsetFactor()
        +isHdMod()
    }