classDiagram
    class StaticTextMessage {
    }
    class StaticText {
        +drawText()
        +getName()
        +getText()
        +getMessageMode()
        +getFirstMessage()
        +isYell()
        +setText()
        +setFont()
        +addMessage()
        +addColoredMessage()
        +asStaticText()
        +isStaticText()
        +setColor()
        +getColor()
        +hasText()
    }