classDiagram
    class TextRenderCache {
    }
    class TextRender {
        +init()
        +terminate()
        +poll()
        +addText()
        +drawText()
        +drawText()
        +drawColoredText()
    }