classDiagram
    class MarketData {
    }
    class StoreCategory {
    }
    class StoreOffer {
    }
    class Imbuement {
    }
    class Light {
    }
    class DrawOutfitParams {
    }
    class ThingType {
        +unserialize()
        +unserializeOtml()
        +unload()
        +serialize()
        +exportImage()
        +replaceSprites()
        +drawOutfit()
        +getDrawSize()
        +drawWithShader()
        +drawWithShader()
        +getId()
        +getCategory()
        +isNull()
        +hasAttr()
        +isLoaded()
        +getLastUsage()
        +getSize()
        +getWidth()
        +getHeight()
        +getExactSize()
        ... (63 more members)
    }
    class DrawQueueItemThingWithShader {
    }