classDiagram
    class Tile {
        +calculateCorpseCorrection()
        +drawGround()
        +drawBottom()
        +drawCreatures()
        +drawTop()
        +drawTexts()
        +drawWidget()
        +clean()
        +addWalkingCreature()
        +removeWalkingCreature()
        +addThing()
        +removeThing()
        +getThing()
        +getEffect()
        +hasThing()
        +getThingStackPos()
        +getTopThing()
        +getTopLookThing()
        +getTopLookThingEx()
        +getTopUseThing()
        ... (59 more members)
    }