classDiagram
    class UIItem {
        +drawSelf()
        +setItemId()
        +setItemCount()
        +setItemSubType()
        +setItemVisible()
        +setItem()
        +setVirtual()
        +clearItem()
        +setShowCount()
        +setItemShader()
        +getItemId()
        +getItemCount()
        +getItemSubType()
        +getItemCountOrSubType()
        +getItem()
        +isVirtual()
        +isItemVisible()
        #onStyleApply()
        #cacheCountText()
        #m_item
        ... (6 more members)
    }