classDiagram
    class UIMap {
        +onMouseMove()
        +drawSelf()
        +movePixels()
        +setZoom()
        +zoomIn()
        +zoomOut()
        +followCreature()
        +setCameraPosition()
        +setMaxZoomIn()
        +setMaxZoomOut()
        +setMultifloor()
        +lockVisibleFloor()
        +unlockVisibleFloor()
        +setVisibleDimension()
        +setDrawFlags()
        +setDrawTexts()
        +setDrawNames()
        +setDrawHealthBars()
        +setDrawHealthBarsOnTop()
        +setDrawLights()
        ... (34 more members)
    }