classDiagram
    class UIManager {
        +init()
        +terminate()
        +render()
        +resize()
        +inputEvent()
        +updatePressedWidget()
        +updateDraggingWidget()
        +updateHoveredWidget()
        +clearStyles()
        +importStyle()
        +importStyleFromString()
        +importStyleFromOTML()
        +getStyle()
        +getStyleClass()
        +loadUIFromString()
        +loadUI()
        +displayUI()
        +createWidget()
        +createWidgetFromOTML()
        +setMouseReceiver()
        ... (16 more members)
    }