classDiagram
    class UITextEdit {
        +drawSelf()
        +setCursorPos()
        +setSelection()
        +setCursorVisible()
        +setTextHidden()
        +setValidCharacters()
        +setShiftNavigation()
        +setMultiline()
        +setMaxLength()
        +setTextVirtualOffset()
        +setEditable()
        +setSelectable()
        +setSelectionColor()
        +setSelectionBackgroundColor()
        +setAutoScroll()
        +setAutoSubmit()
        +setPlaceholder()
        +setPlaceholderColor()
        +setPlaceholderAlign()
        +setPlaceholderFont()
        ... (44 more members)
    }