classDiagram
    class VertexArray {
        +m_hardwareBuffer
        +addVertex()
        +addTriangle()
        +addRect()
        +top
        +right
        +bottom
        +left
        +addRect()
        +top
        +right
        +bottom
        +left
        +addQuad()
        +top
        +right
        +bottom
        +left
        +addUpsideDownQuad()
        +top
        ... (8 more members)
    }