# requires: PowerShell 5+
$ErrorActionPreference = 'Stop'

$reportPath = 'docs/authoring/qa/link_lint.csv'
if (-not (Test-Path -LiteralPath $reportPath)) {
  Write-Error "Report not found: $reportPath"; exit 1
}

function Ensure-Directory {
  param([string]$Path)
  if (-not [string]::IsNullOrWhiteSpace($Path)) {
    $dir = [System.IO.Path]::GetDirectoryName($Path)
    if (-not [string]::IsNullOrWhiteSpace($dir) -and -not (Test-Path -LiteralPath $dir)) {
      New-Item -ItemType Directory -Force -Path $dir | Out-Null
    }
  }
}

$rows = Import-Csv -LiteralPath $reportPath
$created = 0
foreach ($r in $rows) {
  if ($r.status -ne 'BROKEN') { continue }
  $mdRel = $r.file
  $link = $r.link
  if ([string]::IsNullOrWhiteSpace($mdRel) -or [string]::IsNullOrWhiteSpace($link)) { continue }

  $mdFull = Join-Path 'docs/authoring' $mdRel
  if (-not (Test-Path -LiteralPath $mdFull)) { continue }

  # Resolve link target relative to the markdown file
  $targetFull = $null
  try {
    $baseDir = Split-Path -LiteralPath $mdFull -Parent
    $targetFull = [System.IO.Path]::GetFullPath((Join-Path $baseDir $link))
  } catch { continue }

  # If link ends with '/', it's a directory link
  if ($link.Trim().EndsWith('/')) {
    if (-not (Test-Path -LiteralPath $targetFull)) {
      New-Item -ItemType Directory -Force -Path $targetFull | Out-Null
      $created++
    }
    continue
  }

  # Create missing file stubs (.md/.mmd), skip other extensions
  $ext = [System.IO.Path]::GetExtension($targetFull).ToLowerInvariant()
  if ($ext -in @('.md', '.mmd')) {
    if (-not (Test-Path -LiteralPath $targetFull)) {
      Ensure-Directory -Path $targetFull
      if ($ext -eq '.md') {
        $title = [System.IO.Path]::GetFileNameWithoutExtension($targetFull) -replace '_',' ' -replace '-',' '
        $content = "---`ntitle: $title`n---`n`n# $title`n`n> Autogenerated placeholder to satisfy link lint.`n"
        [System.IO.File]::WriteAllText($targetFull, $content, (New-Object System.Text.UTF8Encoding($false)))
      } else {
        [System.IO.File]::WriteAllText($targetFull, "%% Autogenerated placeholder diagram", (New-Object System.Text.UTF8Encoding($false)))
      }
      $created++
    }
  }
}
Write-Host "Created $created placeholders for broken links."
