from __future__ import annotations
import os
import re
from pathlib import Path
from sphinx.util import logging as sphinx_logging

logger = sphinx_logging.getLogger(__name__)

project = "OTClient v8 — Developer Documentation"
author = "OTCv8"
language = "pl"

# Źródła: RST + MyST (Markdown)
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "myst",
}

# Motyw
html_theme = "pydata_sphinx_theme"
html_static_path = ["_static"]
templates_path = ["_templates"]

# BaseURL (CLI ma pierwszeństwo, ale dajemy fallback z ENV)
# Placeholder - should be updated to actual GitHub Pages URL
html_baseurl = os.environ.get("SPHINX_HTML_BASEURL", "https://lukaszj321.github.io/otcv8-dev")

extensions = [
    # MyST (Markdown)
    "myst_parser",

    # Sphinx core
    "sphinx.ext.githubpages",
    "sphinx.ext.todo",
    "sphinx.ext.ifconfig",
    "sphinx.ext.duration",
    "sphinx.ext.graphviz",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinx.ext.autosectionlabel",  # Prevent duplicate label errors

    # Dodatki
    "sphinxcontrib.mermaid",
    "sphinx_design",
    "sphinx_copybutton",
    "sphinxext.opengraph",
    "sphinx_sitemap",
    "sphinx_favicon",
    "sphinx_codeautolink",
    "sphinxcontrib.jquery",
    "hoverxref.extension",
    "sphinxext.rediraffe",
]

# Optional extensions - only load if available
try:
    import sphinx_last_updated_by_git
    extensions.append("sphinx_last_updated_by_git")
except ImportError:
    logger.warning("sphinx_last_updated_by_git not available, skipping")

try:
    import ablog
    extensions.append("ablog")
except ImportError:
    logger.warning("ablog not available, skipping")

# Enable autosectionlabel and prefix document to avoid duplicate labels across files
if 'sphinx.ext.autosectionlabel' not in globals().get('extensions', []):
    extensions = globals().get('extensions', []) + ['sphinx.ext.autosectionlabel']

# Prefix autogenerated section labels with the document path
autosectionlabel_prefix_document = True

# Temporary hotfix: suppress duplicate label warnings so CI doesn't fail while we migrate
suppress_warnings = globals().get('suppress_warnings', []) + ['myst.xref_missing', 'ref.duplicate', 'autosectionlabel.*']

# Exclude patterns to avoid duplicate C++ declarations
exclude_patterns = globals().get("exclude_patterns", []) + [
    "autoapi/cpp/*",
    "api/cpp/*",
]

# Jeśli istnieje Doxygen XML – włącz breathe/exhale
_DOXY_XML = Path(__file__).resolve().parent / "_build" / "doxygen" / "xml"
if _DOXY_XML.exists():
    extensions += ["breathe", "exhale"]
    breathe_default_project = "OTCv8 C++ API"
    breathe_projects = {breathe_default_project: str(_DOXY_XML)}
    exhale_args = {
        "containmentFolder": str(Path("api") / "cpp"),
        "rootFileName": "index.rst",
        "rootFileTitle": "C++ API",
        "doxygenStripFromPath": str(Path(__file__).resolve().parent.parent),
        "createTreeView": True,
        "exhaleExecutesDoxygen": False,
        "verboseBuild": False,
    }

# MyST – to czego używasz (tabs, admonitions, listy itd.)
myst_enable_extensions = [
    "colon_fence",
    "linkify",
    "attrs_block",
    "attrs_inline",
    "substitution",
    "tasklist",
    "deflist",
]

# InterSphinx – poprawne: drugi element to None
intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "sphinx": ("https://www.sphinx-doc.org/en/master/", None),
}
intersphinx_timeout = 10  # Reduce timeout to avoid hanging on network issues

# hoverxref – zdefiniuj typy, żeby nie pluł ostrzeżeniami
hoverxref_role_types = {
    "ref": "tooltip",
    "mod": "tooltip",
    "doc": "tooltip",
}

# Sitemap
sitemap_url_scheme = "{link}"

# Codeautolink
codeautolink_autodoc_inject = False

# Mermaid
mermaid_version = os.environ.get("SPHINX_MERMAID_VERSION", "10.9.1")
mermaid_output_format = os.environ.get("SPHINX_MERMAID_OUT", "raw")

# Nie wywalaj buildu na brakujących celach MyST (masz dużo linków między MD)
# Note: suppress_warnings for ref.duplicate is configured earlier (line ~77) using globals().get() pattern

# ----------------- Pygments lexer fallback for unknown languages -----------------
from sphinx.highlighting import lexers
from pygments.lexers.special import TextLexer
from pygments.lexers import get_lexer_by_name

# Map unknown lexers to text to prevent fatal errors
LEXER_FALLBACK_MAP = {
    'mermaid': 'text',
    'otml': 'text',
    'csv': 'text',
    'gradle': 'groovy',  # Gradle is Groovy-based
    'otui': 'text',
    'json5': 'json',
}

# Create a single reusable TextLexer instance for efficiency
_text_lexer_instance = TextLexer()

def _register_fallback_lexers():
    """Register fallback lexers for languages that Pygments doesn't know."""
    for lang, fallback in LEXER_FALLBACK_MAP.items():
        try:
            if fallback == 'text':
                lexers[lang] = _text_lexer_instance
            else:
                # Get the fallback lexer (imported at module level)
                lexers[lang] = get_lexer_by_name(fallback)
            logger.info(f"[conf.py] Registered fallback lexer '{fallback}' for '{lang}'")
        except Exception as e:
            logger.warning(f"[conf.py] Could not register fallback for '{lang}': {e}")
            lexers[lang] = _text_lexer_instance

# Register at module load time
_register_fallback_lexers()

# ----------------- Fix 1: czyść złe dependencies (git) -----------------
def _sanitize_dependencies(env) -> int:
    import os
    changed = 0
    deps = getattr(env, "dependencies", {}) or {}
    for docname, items in list(deps.items()):
        # Ensure items is iterable/list
        items_list = list(items) if items is not None else []
        newset = set()
        for p in items_list:
            if isinstance(p, bytes):
                p = p.decode("utf-8", "ignore")
            p = str(p).strip()
            if not p:
                continue
            # wywal katalogi i ścieżki bez rozszerzenia (np. 'diagrams')
            if p.endswith("/") or os.path.splitext(p)[1] == "":
                continue
            newset.add(p)
        # Porównanie jako zbiory (kolejność nieistotna)
        if set(newset) != set(items_list):
            deps[docname] = list(newset)
            changed += 1
    return changed

def _pre_git_filter(app, env):
    try:
        _sanitize_dependencies(env)
    except Exception as e:
        logger.warning(f"[conf.py] dependency sanitize failed: {e}")

# ----------------- Fix 2: puste bloki Breathe (.. doxygenenum::) ------
_DOXY_EMPTY_BLOCK_RE = re.compile(
    r"(?ms)^\.\.\s+doxygen(?:enum|class|struct|union|function)\s*::\s*$\n"
    r"(?:^[ \t]*:[a-zA-Z0-9_-]+:.*\n)*"
)

def _fix_breathe_empty_blocks(app, docname, source):
    s = source[0]
    if ".. doxygen" not in s:
        return
    def _repl(_m):
        return ".. note:: (pominięto pustą dyrektywę wygenerowaną przez Exhale)\n\n"
    ns, nsubs = _DOXY_EMPTY_BLOCK_RE.subn(_repl, s)
    if nsubs:
        source[0] = ns
        logger.info(f"[conf.py] fixed {nsubs} empty doxygen* blocks in {docname}")

# ----------------- Fix 3: Tab-item sanitizer for sphinx-design -----------------
def _sanitize_tab_items(app, docname, source):
    """
    Sanitize malformed tab-item constructs before Sphinx processes them.
    
    This function handles both RST (.. tab-set:: / .. tab-item::) and 
    MyST/Markdown (:::{tab-set} / :::{tab-item} Label) syntax.
    
    Fixes applied:
    1. Tab-items with no body content get placeholder: "TBD: documentation content"
    2. Tab-items missing labels get placeholder label: "Untitled"
    """
    s = source[0]
    
    # Skip if no tab constructs present
    if "tab-item" not in s and "tab-set" not in s:
        return
    
    modified = False
    
    # ===== MyST/Markdown tab-item handling (:::{tab-item} Label) =====
    # Pattern: :::{tab-item} followed by optional label, optional directives, then either ::: or end
    # Match group 1: indentation, group 2: label (optional), group 3: content until closing :::
    myst_pattern = re.compile(
        r'^([ \t]*)(:::)\{tab-item\}[ \t]*([^\n]*)\n'  # Opening with optional label
        r'((?:^[ \t]*:[a-zA-Z0-9_-]+:.*\n)*?)'        # Optional directives (like :sync:)
        r'(.*?)'                                        # Content (may be empty)
        r'^([ \t]*)(:::)(?=\s|$)',                     # Closing :::
        re.MULTILINE | re.DOTALL
    )
    
    def _fix_myst_tab_item(match):
        nonlocal modified
        indent = match.group(1)
        opening = match.group(2)  # :::
        label = match.group(3).strip()
        directives = match.group(4)
        content = match.group(5)
        closing_indent = match.group(6)
        closing = match.group(7)  # :::
        
        # Check if label is missing or empty
        if not label:
            label = "Untitled"
            logger.info(f"[conf.py] {docname}: Added placeholder label 'Untitled' to MyST tab-item")
            modified = True
        
        # Check if content is empty or only whitespace
        if not content.strip():
            content = "\nTBD: documentation content\n\n"
            logger.info(f"[conf.py] {docname}: Added placeholder content to empty MyST tab-item '{label}'")
            modified = True
        
        # Reconstruct the tab-item
        return f"{indent}{opening}{{tab-item}} {label}\n{directives}{content}{closing_indent}{closing}"
    
    s = myst_pattern.sub(_fix_myst_tab_item, s)
    
    # ===== RST tab-item handling (.. tab-item::) =====
    # Pattern: .. tab-item:: followed by optional label, optional directives, then content
    rst_pattern = re.compile(
        r'^([ \t]*)\.\.\s+tab-item::[ \t]*([^\n]*)\n'  # Opening with optional label
        r'((?:^[ \t]+:[a-zA-Z0-9_-]+:.*\n)*?)'         # Optional directives (indented)
        r'((?:^[ \t]*\n)*?)'                            # Optional blank lines
        r'((?:^(?:[ \t]+\S.*|[ \t]*)$\n)*?)'           # Content (indented or blank)
        r'(?=^(?:[ \t]*\.\.|[ \t]*:::|\Z))',           # Lookahead: next directive/closing or end
        re.MULTILINE
    )
    
    def _fix_rst_tab_item(match):
        nonlocal modified
        indent = match.group(1)
        label = match.group(2).strip()
        directives = match.group(3)
        blank_lines = match.group(4)
        content = match.group(5)
        
        # Check if label is missing
        if not label:
            label = "Untitled"
            logger.info(f"[conf.py] {docname}: Added placeholder label 'Untitled' to RST tab-item")
            modified = True
        
        # Check if content is empty
        content_stripped = content.strip()
        if not content_stripped:
            # Add indented placeholder content
            content = f"{indent}   TBD: documentation content\n\n"
            blank_lines = "\n"
            logger.info(f"[conf.py] {docname}: Added placeholder content to empty RST tab-item '{label}'")
            modified = True
        
        # Reconstruct the tab-item
        return f"{indent}.. tab-item:: {label}\n{directives}{blank_lines}{content}"
    
    s = rst_pattern.sub(_fix_rst_tab_item, s)
    
    if modified:
        source[0] = s
        logger.info(f"[conf.py] Sanitized tab-items in {docname}")

# ----------------- hooki -----------------
def setup(app):
    # uruchom porządkowanie PRZED last_updated_by_git (niższy priorytet = wcześniej)
    app.connect("env-updated", _pre_git_filter, priority=100)
    # podmień puste bloki Breathe zaraz po wczytaniu źródła
    app.connect("source-read", _fix_breathe_empty_blocks, priority=500)
    # sanitize tab-items before processing (run early, before sphinx-design)
    app.connect("source-read", _sanitize_tab_items, priority=400)
