%%{init: {'theme':'dark','securityLevel':'loose','themeVariables':{'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}}}%%
graph TD
    A[VC16/ANGLE] --> B[Components]
    A --> C[Datasets]
    A --> D[Diagrams]
\nclick Overview "./index.html#facet-15_vc16.overview" "Open overview"\n