%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
    Sln[Solution] --> Core[Core]
    Sln --> Client[Client]
    click Core "./index.html#facet-15_vc16.projects" "Open projects dataset"
click SolutionGraph "./index.html#facet-15_vc16.solution_graph" "Open solution_graph"