%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
  ModuleArchitecture[03_modules:modules_architecture] --> Data[Datasets]
  Data --> Page[Index]

click ModuleArchitecture "./index.html#facet-03_modules.modules_architecture" "Open modules_architecture"
