%%{init: { 'theme': 'neutral' }}%%
flowchart TD
  DATA[data/**]-->IMAGES[images/**]
  DATA-->FONTS[fonts/**]
  DATA-->STYLES[styles/**]
  DATA-->LOCALES[locales/**]
  DATA-->SHADERS[shaders/**]
  DATA-->SOUNDS[sounds/**]
  LAYOUTS[layouts/<name>/**]-->DATA
