%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Adaptiverenderer {
        +newFrame
        +refresh
        +effetsLimit
        +creaturesLimit
        +itemsLimit
        +textsLimit
        +mapRenderInterval
        +creaturesRenderInterval
        +allowFading
        +getLevel
        +... (3 more methods)
    }
