%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Androidwindow {
        +EventType
        +NativeMessage
        +internalInitGL
        +internalDestroyGL
        +internalCheckGL
        +internalChooseGL
        +internalCreateGLContext
        +internalDestroyGLContext
        +internalConnectGLContext
        +init
        +... (32 more methods)
    }
