%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Animatedtexture["Animatedtexture<br/>────────────<br/>+ replace<br/>+ update<br/>+ isAnimatedTexture<br/>+ buildHardwareMipmaps<br/>+ setSmooth<br/>+ setRepeat<br/>"]:::api
