%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Application {
        +restart
        +restartArgs
        +setName
        +setCompactName
        +setVersion
        +isRunning
        +isStopping
        +isTerminated
        +getCharset
        +getBuildCompiler
        +... (11 more methods)
    }
