%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Application["Application<br/>────────────<br/>+ init<br/>+ deinit<br/>+ terminate<br/>+ run<br/>+ poll<br/>+ exit<br/>+ quick_exit<br/>+ close<br/>+ restart<br/>+ restartArgs<br/>+ setName<br/>+ setCompactName<br/>+ setVersion<br/>+ isRunning<br/>+ isStopping<br/>+ isTerminated<br/>+ getCharset<br/>+ getBuildCompiler<br/>+ getBuildDate<br/>+ getBuildRevision<br/><i>(+ 19 more members)</i><br/>"]:::api
