%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Binarytree["Binarytree<br/>────────────<br/>+ seek<br/>+ skip<br/>+ tell<br/>+ size<br/>+ getU8<br/>+ getU16<br/>+ getU32<br/>+ getU64<br/>+ getString<br/>+ getPoint<br/>+ getChildren<br/>+ canRead<br/>"]:::api
