%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Binarytree["Binarytree<br/>────────────<br/>+ `seek`<br/>+ `skip`<br/>+ `tell`<br/>+ `size`<br/>+ `getU8`<br/>... 16 more<br/>"]:::api
