%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Bitmapfont {
        +load()
        +drawText()
        +drawText()
        +drawColoredText()
        +calculateDrawTextCoords()
        +calculateTextRectSize()
        +wrapText()
        +getId()
        +getName()
        +getGlyphHeight()
        +getYOffset()
        +getGlyphSpacing()
        +calculateGlyphsWidthsAutomatically()
        +updateColors()
        +align()
    }
