%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Cachedtext {
        +draw
        +wrapText
        +setFont
        +setText
        +setColoredText
        +setAlign
        +getTextSize
        +getText
        +getFont
        +getAlign
        +... (2 more methods)
    }
