%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Cachedtext["Cachedtext<br/>────────────<br/>+ draw<br/>+ wrapText<br/>+ setFont<br/>+ setText<br/>+ setColoredText<br/>+ setAlign<br/>+ getTextSize<br/>+ getText<br/>+ getFont<br/>+ getAlign<br/>+ hasText<br/>"]:::api
