%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Cast {
        +stdext
        +cast
        +cast
        +cast
        +cast
        +if
        +cast
        +cast
        +cast
        +cast
        +... (5 more methods)
    }
