%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Clock["Clock<br/>────────────<br/>+ update<br/>+ micros<br/>+ millis<br/>+ seconds<br/>+ realMicros<br/>+ realMillis<br/>"]:::api
