%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Color {
        +a()
        +b()
        +g()
        +r()
        +aF()
        +bF()
        +gF()
        +rF()
        +setRed()
        +setGreen()
        +setBlue()
        +setAlpha()
        +setRed()
        +setGreen()
        +setBlue()
        +setAlpha()
        +setRGBA()
        +setRGBA()
        +opacity()
        +Color()
        +Color()
        +toHex()
        +to8bit()
        +from8bit()
        +Color()
        +Color()
        +getOutfitColor()
        +operator()
        +true()
        +c()
    }
