%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Color {
        +a
        +b
        +g
        +r
        +aF
        +bF
        +gF
        +rF
        +setRed
        +setGreen
        +... (17 more methods)
    }
