%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Colorarray["Colorarray<br/>────────────<br/>+ `addColor`<br/>+ `addColor`<br/>+ `clear`<br/>+ `colorCount`<br/>+ `count`<br/>... 1 more<br/>"]:::api
