%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Color["Color<br/>────────────<br/>+ `a`<br/>+ `b`<br/>+ `g`<br/>+ `r`<br/>+ `aF`<br/>... 29 more<br/>"]:::api
