%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Combinedsoundsource["Combinedsoundsource<br/>────────────<br/>+ `addSource`<br/>+ `getSources`<br/>+ `play`<br/>+ `stop`<br/>+ `isBuffering`<br/>... 10 more<br/>"]:::api
