%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Combinedsoundsource["Combinedsoundsource<br/>────────────<br/>+ addSource<br/>+ getSources<br/>+ play<br/>+ stop<br/>+ isBuffering<br/>+ isPlaying<br/>+ setLooping<br/>+ setRelative<br/>+ setReferenceDistance<br/>+ setGain<br/>+ setPitch<br/>+ setPosition<br/>+ setVelocity<br/>+ setFading<br/>+ update<br/>"]:::api
