%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Configmanager["Configmanager<br/>────────────<br/>+ `init`<br/>+ `terminate`<br/>+ `getSettings`<br/>+ `get`<br/>+ `create`<br/>... 5 more<br/>"]:::api
