%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Coordsbuffer["Coordsbuffer<br/>────────────<br/>+ `clear`<br/>+ `addTriangle`<br/>+ `addRect`<br/>+ `addRect`<br/>+ `addRect`<br/>... 9 more<br/>"]:::api
