%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Crypt["Crypt<br/>────────────<br/>+ `base64Encode`<br/>+ `base64Decode`<br/>+ `xorCrypt`<br/>+ `encrypt`<br/>+ `decrypt`<br/>... 17 more<br/>"]:::api
