%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Crypt {
        +base64Encode
        +base64Decode
        +xorCrypt
        +encrypt
        +decrypt
        +genUUID
        +setMachineUUID
        +getMachineUUID
        +md5Encode
        +sha1Encode
        +... (16 more methods)
    }
