%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Databuffer["Databuffer<br/>────────────<br/>+ `reset`<br/>+ `clear`<br/>+ `empty`<br/>+ `size`<br/>+ `reserve`<br/>... 4 more<br/>"]:::api
