%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Deptharray["Deptharray<br/>────────────<br/>+ `addDepth`<br/>+ `clear`<br/>+ `depthCount`<br/>+ `count`<br/>+ `size`<br/>"]:::api
