%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Drawqueue {
        +DrawType()
        +draw()
        +draw()
        +cache()
        +draw()
        +draw()
        +draw()
        +cache()
        +cache()
        +draw()
        +cache()
        +draw()
        +draw()
        +draw()
        +start()
        +end()
        +start()
        +end()
        +start()
        +end()
        +draw()
        +add()
        +addTextureCoords()
        +addColoredTextureCoords()
        +addFilledRect()
        +addFillCoords()
        +addClearRect()
        +addText()
        +addColoredText()
        +addFilledTriangle()
        +addBoundingRect()
        +addLine()
        +setFrameBuffer()
        +hasFrameBuffer()
        +getFrameBufferDest()
        +getFrameBufferSize()
        +getFrameBufferSrc()
        +size()
        +setOpacity()
        +setClip()
        +setRotation()
        +setMark()
        +markMapPosition()
        +correctOutfit()
        +setShader()
        +getShader()
    }
