%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Drawcache {
        +draw
        +bind
        +release
        +hasSpace
        +getSize
        +addRect
        +addTexturedRect
        +addCoords
        +addTexturedCoords
        +addRectRaw
        +... (1 more methods)
    }
