%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Event["Event<br/>────────────<br/>+ `execute`<br/>+ `cancel`<br/>+ `isCanceled`<br/>+ `isExecuted`<br/>+ `isBotSafe`<br/>... 5 more<br/>"]:::api
