%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Eventdispatcher["Eventdispatcher<br/>────────────<br/>+ shutdown<br/>+ poll<br/>+ addEventEx<br/>+ scheduleEventEx<br/>+ cycleEventEx<br/>+ isBotSafe<br/>"]:::api
