%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Filestream {
        +close
        +flush
        +write
        +read
        +seek
        +skip
        +size
        +tell
        +eof
        +name
        +... (27 more methods)
    }
