%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Filestream["Filestream<br/>────────────<br/>+ close<br/>+ flush<br/>+ write<br/>+ read<br/>+ seek<br/>+ skip<br/>+ size<br/>+ tell<br/>+ eof<br/>+ name<br/>+ getU8<br/>+ getU16<br/>+ getU32<br/>+ getU64<br/>+ get8<br/>+ get16<br/>+ get32<br/>+ get64<br/>+ getString<br/>+ getBinaryTree<br/><i>(+ 14 more members)</i><br/>"]:::api
