%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Fontmanager["Fontmanager<br/>────────────<br/>+ terminate<br/>+ clearFonts<br/>+ importFont<br/>+ fontExists<br/>+ getFont<br/>+ getDefaultFont<br/>+ setDefaultFont<br/>"]:::api
