%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Framebuffermanager["Framebuffermanager<br/>────────────<br/>+ `init`<br/>+ `terminate`<br/>+ `clear`<br/>+ `createFrameBuffer`<br/>+ `m_temporaryFramebuffer`<br/>... 2 more<br/>"]:::api
