%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Graphics {
        +init
        +terminate
        +resize
        +checkDepthSupport
        +getMaxTextureSize
        +getVendor
        +getRenderer
        +getVersion
        +getExtensions
        +ok
        +... (2 more methods)
    }
