%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Hardwarebuffer["Hardwarebuffer<br/>────────────<br/>+ `bind`<br/>+ `unbind`<br/>+ `write`<br/>"]:::api
