%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Http["Http<br/>────────────<br/>+ `init`<br/>+ `terminate`<br/>+ `get`<br/>+ `post`<br/>+ `download`<br/>... 10 more<br/>"]:::api
