%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Image["Image<br/>────────────<br/>+ `load`<br/>+ `loadPNG`<br/>+ `loadPNG`<br/>+ `savePNG`<br/>+ `blit`<br/>... 12 more<br/>"]:::api
