%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Image["Image<br/>────────────<br/>+ load<br/>+ loadPNG<br/>+ loadPNG<br/>+ savePNG<br/>+ blit<br/>+ paste<br/>+ upscale<br/>+ resize<br/>+ nextMipmap<br/>+ setPixel<br/>+ setPixel<br/>+ setPixel<br/>+ getPixelCount<br/>+ getWidth<br/>+ getHeight<br/>+ getBpp<br/>+ fromQRCode<br/>"]:::api
