%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Inputmessage["Inputmessage<br/>────────────<br/>+ setBuffer<br/>+ getBuffer<br/>+ getBodyBuffer<br/>+ skipBytes<br/>+ setReadPos<br/>+ getU8<br/>+ getU16<br/>+ getU32<br/>+ getU64<br/>+ getString<br/>+ getDouble<br/>+ peekU8<br/>+ peekU16<br/>+ peekU32<br/>+ peekU64<br/>+ decryptRsa<br/>+ getHeaderPos<br/>+ getHeaderSize<br/>+ getReadSize<br/>+ getReadPos<br/><i>(+ 10 more members)</i><br/>"]:::api
