%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Logger {
        +log()
        +logFunc()
        +debug()
        +info()
        +warning()
        +error()
        +fatal()
        +fireOldMessages()
        +setLogFile()
        +setOnLog()
        +getLastLog()
        +setTestingMode()
        +OnLogCallback()
        +m_lastLog()
    }
