%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Luabinder {
        +luabinder()
        +call()
        +call()
        +call()
        +call()
        +bind_fun_specializer()
        +bind_fun()
        +bind_fun()
        +call()
        +decltype()
        +bind_fun()
        +bind_fun()
        +LuaException()
        +mf()
        +LuaException()
        +make_mem_func_singleton()
        +make_mem_func_singleton()
        +bind_mem_fun()
        +bind_singleton_mem_fun()
        +bind_mem_fun()
        +mf()
        +ValueType()
        +Tuple()
        +Tuple()
        +F()
        +Tuple()
        +Tuple()
    }
