%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Luabinder {
        +luabinder
        +call
        +call
        +call
        +call
        +bind_fun_specializer
        +bind_fun
        +bind_fun
        +call
        +decltype
        +... (17 more methods)
    }
