%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Luainterface["Luainterface<br/>────────────<br/>+ init<br/>+ terminate<br/>+ registerFunctions<br/>+ registerSingletonClass<br/>+ registerClass<br/>+ registerClass<br/>+ registerClassStaticFunction<br/>+ registerClassMemberFunction<br/>+ bindSingletonFunction<br/>+ bindSingletonFunction<br/>+ bindSingletonFunction<br/>+ bindClassStaticFunction<br/>+ bindClassStaticFunction<br/>+ bindClassMemberFunction<br/>+ bindClassMemberFunction<br/>+ bindClassMemberField<br/>+ bindClassMemberField<br/>+ bindClassMemberGetField<br/>+ bindClassMemberGetField<br/>+ bindClassMemberSetField<br/><i>(+ 105 more members)</i><br/>"]:::api
