%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Luainterface["Luainterface<br/>────────────<br/>+ `init`<br/>+ `terminate`<br/>+ `registerFunctions`<br/>+ `registerSingletonClass`<br/>+ `registerClass`<br/>... 227 more<br/>"]:::api
