%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Luaobject["Luaobject<br/>────────────<br/>+ connectLuaField<br/>+ luaCallLuaField<br/>+ callLuaField<br/>+ callLuaField<br/>+ hasLuaField<br/>+ setLuaField<br/>+ getLuaField<br/>+ releaseLuaFieldsTable<br/>+ luaSetField<br/>+ luaGetField<br/>+ luaGetMetatable<br/>+ luaGetFieldsTable<br/>+ getUseCount<br/>+ getClassName<br/>+ asLuaObject<br/>+ operator<br/>"]:::api
