%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Luavaluecasts {
        +push_internal_luavalue
        +push_luavalue
        +luavalue_cast
        +push_luavalue
        +luavalue_cast
        +push_luavalue
        +luavalue_cast
        +push_luavalue
        +luavalue_cast
        +push_luavalue
        +... (66 more methods)
    }
