%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Luavaluecasts {
        +push_internal_luavalue()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +luavalue_cast()
        +push_luavalue()
        +push_internal_luavalue()
        +push_internal_luavalue()
        +push_luavalue()
        +push_luavalue()
        +luavalue_cast()
        +LuaException()
        +Ret()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +push_luavalue()
        +luavalue_cast()
        +luavalue_cast()
        +call()
        +call()
        +push_internal_luavalue()
        +call()
        +call()
        +push_luavalue()
    }
