%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Matrix {
        +setIdentity
        +isIdentity
        +fill
        +transposed
        +operator
        +result
        +c
        +Matrix4x4
        +Matrix3x3
        +Matrix2x2
        +... (3 more methods)
    }
