%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Modulemanager["Modulemanager<br/>────────────<br/>+ clear<br/>+ discoverModules<br/>+ autoLoadModules<br/>+ discoverModule<br/>+ ensureModuleLoaded<br/>+ unloadModules<br/>+ reloadModules<br/>+ getModule<br/>+ getModules<br/>+ updateModuleLoadOrder<br/>"]:::api
