%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Mouse["Mouse<br/>────────────<br/>+ `init`<br/>+ `terminate`<br/>+ `loadCursors`<br/>+ `addCursor`<br/>+ `pushCursor`<br/>... 3 more<br/>"]:::api
