%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Oggsoundfile {
        +prepareOgg
        +read
        +reset
        +cb_read
        +cb_seek
        +cb_close
        +cb_tell
    }
