%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Otmlnode["Otmlnode<br/>────────────<br/>+ `create`<br/>+ `create`<br/>+ `tag`<br/>+ `size`<br/>+ `source`<br/>... 42 more<br/>"]:::api
