%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Otmlnode["Otmlnode<br/>────────────<br/>+ create<br/>+ create<br/>+ tag<br/>+ size<br/>+ source<br/>+ rawValue<br/>+ isUnique<br/>+ isNull<br/>+ hasTag<br/>+ hasValue<br/>+ hasChildren<br/>+ hasChildAt<br/>+ getIndex<br/>+ setTag<br/>+ setValue<br/>+ setNull<br/>+ setUnique<br/>+ setSource<br/>+ setIndex<br/>+ lockTag<br/><i>(+ 27 more members)</i><br/>"]:::api
