%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Outputmessage {
        +reset
        +setBuffer
        +getBuffer
        +addU8
        +addU16
        +addU32
        +addU64
        +addString
        +addRawString
        +addPaddingBytes
        +... (10 more methods)
    }
