%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Painter {
        +BlendEquation()
        +CompositionMode()
        +DepthFunc()
        +DrawMode()
        +bind()
        +unbind()
        +resetState()
        +refreshState()
        +saveState()
        +saveAndResetState()
        +restoreSavedState()
        +clear()
        +clearRect()
        +setTransformMatrix()
        +setProjectionMatrix()
        +setTextureMatrix()
        +setCompositionMode()
        +setBlendEquation()
        +setDepthFunc()
        +setClipRect()
        +setShaderProgram()
        +setTexture()
        +setAlphaWriting()
        +setResolution()
        +scale()
        +translate()
        +rotate()
        +rotate()
        +pushTransformMatrix()
        +popTransformMatrix()
        +getTransformMatrix()
        +getProjectionMatrix()
        +getTextureMatrix()
        +getBlendEquation()
        +getAlphaWriting()
        +resetBlendEquation()
        +resetTexture()
        +resetAlphaWriting()
        +resetTransformMatrix()
        +drawCoords()
        +drawFillCoords()
        +drawTextureCoords()
        +drawTexturedRect()
        +drawTexturedRect()
        +drawColorOnTexturedRect()
        +drawUpsideDownTexturedRect()
        +drawRepeatedTexturedRect()
        +drawFilledRect()
        +setDrawProgram()
        +hasShaders()
        +drawText()
        +drawText()
        +drawLine()
        +setSecondTexture()
        +setOffset()
        +setAtlasTextures()
        +drawCache()
        +setColor()
        +setShaderProgram()
        +scale()
        +translate()
        +rotate()
        +setDepth()
        +getDepth()
        +getDepthFunc()
        +resetDepth()
        +resetDepthFunc()
        +getResolution()
        +getColor()
        +getClipRect()
        +getCompositionMode()
        +resetClipRect()
        +resetCompositionMode()
        +resetColor()
        +resetShaderProgram()
        +draws()
        +calls()
        +resetDraws()
        +setDrawColorOnTextureShaderProgram()
        +setMatrixColor()
        +setDrawOutfitLayersProgram()
        +updateGlTexture()
        +updateGlCompositionMode()
        +updateGlBlendEquation()
        +updateGlClipRect()
        +updateGlAlphaWriting()
        +updateGlViewport()
        +updateDepthFunc()
    }
