%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Paintershaderprogram {
        +link
        +setTransformMatrix
        +setProjectionMatrix
        +setTextureMatrix
        +setColor
        +setMatrixColor
        +setDepth
        +setResolution
        +setOffset
        +setCenter
        +... (5 more methods)
    }
