%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Platformwindow {
        +loadMouseCursor
        +hasVerticalSync
        +getDisplayWidth
        +getDisplayHeight
        +getUnmaximizedSize
        +getSize
        +getMinimumSize
        +getWidth
        +getHeight
        +getUnmaximizedPos
        +... (22 more methods)
    }
