%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Platform["Platform<br/>────────────<br/>+ `processArgs`<br/>+ `spawnProcess`<br/>+ `getProcessId`<br/>+ `isProcessRunning`<br/>+ `killProcess`<br/>... 18 more<br/>"]:::api
