%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Platformwindow {
        +loadMouseCursor()
        +hasVerticalSync()
        +getDisplayWidth()
        +getDisplayHeight()
        +getUnmaximizedSize()
        +getSize()
        +getMinimumSize()
        +getWidth()
        +getHeight()
        +getUnmaximizedPos()
        +getPosition()
        +getX()
        +getY()
        +getMousePosition()
        +getKeyboardModifiers()
        +isKeyPressed()
        +isMouseButtonPressed()
        +isVisible()
        +isMaximized()
        +isFullscreen()
        +hasFocus()
        +setOnClose()
        +setOnResize()
        +setOnInputEvent()
        +setScaling()
        +updateUnmaximizedCoords()
        +processKeyDown()
        +processKeyUp()
        +releaseAllKeys()
        +fireKeysPress()
        +OnResizeCallback()
        +OnInputEventCallback()
        +init()
        +terminate()
        +move()
        +resize()
        +show()
        +hide()
        +minimize()
        +maximize()
        +poll()
        +swapBuffers()
        +showMouse()
        +hideMouse()
        +displayFatalError()
        +setMouseCursor()
        +restoreMouseCursor()
        +setTitle()
        +setMinimumSize()
        +setFullscreen()
        +setVerticalSync()
        +setIcon()
        +setClipboardText()
        +getDisplaySize()
        +getClipboardText()
        +getPlatformType()
        +showTextEditor()
        +handleTextInput()
        +flash()
        +internalLoadMouseCursor()
        +m_keyMap()
        +m_firstKeysPress()
        +m_lastKeysPress()
        +m_keyPressTimer()
        +m_size()
        +m_minimumSize()
        +m_position()
        +m_unmaximizedSize()
        +m_unmaximizedPos()
        +m_inputEvent()
        +m_created()
        +m_visible()
        +m_focused()
        +m_fullscreen()
        +m_maximized()
        +m_verticalSync()
        +m_scaling()
        +m_onClose()
        +m_onResize()
        +m_onInputEvent()
    }
