%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class ProxyClient {
        +ProxyState
        +m_io
        +start
        +terminate
        +getPing
        +getRealPing
        +getPriority
        +isConnected
        +getHost
        +getPort
        +... (32 more methods)
    }
