%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Qrcodegen {
        +qrcodegen_Ecc
        +qrcodegen_Mask
        +qrcodegen_Mode
        +qrcodegen_Mode
        +qrcodegen_Ecc
        +qrcodegen_Ecc
        +qrcodegen_Ecc
        +qrcodegen_isAlphanumeric
        +qrcodegen_isNumeric
        +qrcodegen_calcSegmentBufferSize
        +... (2 more methods)
    }
