%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Rect {
        +isNull()
        +isEmpty()
        +isValid()
        +left()
        +top()
        +right()
        +bottom()
        +horizontalCenter()
        +verticalCenter()
        +x()
        +y()
        +topLeft()
        +bottomRight()
        +topRight()
        +bottomLeft()
        +topCenter()
        +bottomCenter()
        +centerLeft()
        +centerRight()
        +center()
        +width()
        +height()
        +size()
        +reset()
        +clear()
        +setLeft()
        +setTop()
        +setRight()
        +setBottom()
        +setX()
        +setY()
        +setTopLeft()
        +setBottomRight()
        +setTopRight()
        +setBottomLeft()
        +setWidth()
        +setHeight()
        +setSize()
        +setRect()
        +setCoords()
        +expandLeft()
        +expandTop()
        +expandRight()
        +expandBottom()
        +expand()
        +expand()
        +translate()
        +translate()
        +resize()
        +resize()
        +move()
        +move()
        +moveLeft()
        +moveTop()
        +moveRight()
        +moveBottom()
        +moveTopLeft()
        +moveBottomRight()
        +moveTopRight()
        +moveBottomLeft()
        +moveTopCenter()
        +moveBottomCenter()
        +moveCenterLeft()
        +moveCenterRight()
        +translated()
        +translated()
        +expanded()
        +moveCenter()
        +moveHorizontalCenter()
        +moveVerticalCenter()
        +contains()
        +contains()
        +intersects()
        +united()
        +intersection()
        +bind()
        +alignIn()
        +if()
        +if()
        +if()
        +if()
        +if()
        +if()
        +if()
        +if()
        +Rect()
        +RectF()
        +w()
        +h()
        +false()
        +true()
        +l1()
        +r1()
        +l2()
        +r2()
        +t1()
        +b1()
        +t2()
        +b2()
        +tmp()
        +r()
        +operator()
    }
