%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Rect["Rect<br/>────────────<br/>+ `isNull`<br/>+ `isEmpty`<br/>+ `isValid`<br/>+ `left`<br/>+ `top`<br/>... 362 more<br/>"]:::api
