%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Rect {
        +isNull
        +isEmpty
        +isValid
        +left
        +top
        +right
        +bottom
        +horizontalCenter
        +verticalCenter
        +x
        +... (77 more methods)
    }
