%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Resourcemanager["Resourcemanager<br/>────────────<br/>+ init<br/>+ terminate<br/>+ launchCorrect<br/>+ setupWriteDir<br/>+ setup<br/>+ getCompactName<br/>+ loadDataFromSelf<br/>+ fileExists<br/>+ directoryExists<br/>+ readFileStream<br/>+ readFileContents<br/>+ readFileContentsSafe<br/>+ isFileEncryptedOrCompressed<br/>+ writeFileBuffer<br/>+ writeFileContents<br/>+ writeFileStream<br/>+ openFile<br/>+ appendFile<br/>+ createFile<br/>+ deleteFile<br/><i>(+ 28 more members)</i><br/>"]:::api
