%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Scheduledevent["Scheduledevent<br/>────────────<br/>+ execute<br/>+ nextCycle<br/>+ ticks<br/>+ remainingTicks<br/>+ delay<br/>+ cyclesExecuted<br/>+ maxCycles<br/>"]:::api
