%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class SharedObject {
        +stdext()
        +std()
        +add_ref()
        +dec_ref()
        +ref_count()
        +reset()
        +reset()
        +swap()
        +use_count()
        +is_unique()
        +unspecified_bool_type()
        +add_ref()
        +dec_ref()
        +element_type()
    }
