%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Size["Size<br/>────────────<br/>+ `toPoint`<br/>+ `isNull`<br/>+ `isEmpty`<br/>+ `isValid`<br/>+ `width`<br/>... 14 more<br/>"]:::api
