%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Soundmanager {
        +init
        +terminate
        +poll
        +setAudioEnabled
        +isAudioEnabled
        +enableAudio
        +disableAudio
        +stopAll
        +preload
        +play
        +... (4 more methods)
    }
