%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Soundfile["Soundfile<br/>────────────<br/>+ loadSoundFile<br/>+ read<br/>+ reset<br/>+ eof<br/>+ getSampleFormat<br/>+ getChannels<br/>+ getRate<br/>+ getBps<br/>+ getSize<br/>+ getName<br/>+ m_file<br/>+ m_channels<br/>+ m_rate<br/>+ m_bps<br/>+ m_size<br/>"]:::api
