%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Soundfile["Soundfile<br/>────────────<br/>+ `loadSoundFile`<br/>+ `read`<br/>+ `reset`<br/>+ `eof`<br/>+ `getSampleFormat`<br/>... 10 more<br/>"]:::api
