%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Soundmanager["Soundmanager<br/>────────────<br/>+ init<br/>+ terminate<br/>+ poll<br/>+ setAudioEnabled<br/>+ isAudioEnabled<br/>+ enableAudio<br/>+ disableAudio<br/>+ stopAll<br/>+ preload<br/>+ play<br/>+ getChannel<br/>+ resolveSoundFile<br/>+ ensureContext<br/>"]:::api
