%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Stats {
        +StatsTypes()
        +add()
        +get()
        +clear()
        +clearAll()
        +getSlow()
        +clearSlow()
        +types()
        +getSleepTime()
        +resetSleepTime()
        +addWidget()
        +removeWidget()
        +getWidgetsInfo()
        +addTexture()
        +removeTexture()
        +addThing()
        +removeThing()
        +addCreature()
        +removeCreature()
        +StatsMap()
        +StatsList()
        +m_sleepTime()
    }
