%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Streamsoundsource["Streamsoundsource<br/>────────────<br/>+ play<br/>+ stop<br/>+ isPlaying<br/>+ setSoundFile<br/>+ downMix<br/>+ update<br/>"]:::api
