%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Texture {
        +resize()
        +setTime()
        +setCanCache()
        +getId()
        +getUniqueId()
        +getTime()
        +getWidth()
        +getHeight()
        +isEmpty()
        +hasRepeat()
        +hasMipmaps()
        +canCache()
        +uploadPixels()
        +setupSize()
        +setupWrap()
        +setupFilters()
        +setupTranformMatrix()
        +setupPixels()
        +replace()
        +update()
        +setUpsideDown()
        +setSmooth()
        +setRepeat()
        +buildHardwareMipmaps()
        +isAnimatedTexture()
        +m_id()
        +m_uniqueId()
        +m_time()
        +m_size()
        +m_transformMatrix()
        +m_hasMipmaps()
        +m_smooth()
        +m_upsideDown()
        +m_repeat()
        +m_buildHardwareMipmaps()
        +m_needsUpdate()
        +m_canCache()
        +m_image()
    }
