%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Time {
        +stdext
        +time
        +millis
        +micros
        +millisleep
        +microsleep
        +elapsed_seconds
        +elapsed_millis
        +elapsed_micros
        +restart
    }
