%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Timer["Timer<br/>────────────<br/>+ `restart`<br/>+ `stop`<br/>+ `adjust`<br/>+ `startTicks`<br/>+ `ticksElapsed`<br/>... 2 more<br/>"]:::api
