%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Tinyxml {
        +TiXmlEncoding
        +NodeType
        +Clear
        +Accept
        +SetCondenseWhiteSpace
        +IsWhiteSpaceCondensed
        +Row
        +Column
        +SetUserData
        +EncodeString
        +... (95 more methods)
    }
