%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Tinyxml["Tinyxml<br/>────────────<br/>+ `VisitEnter`<br/>+ `VisitExit`<br/>+ `VisitEnter`<br/>+ `VisitExit`<br/>+ `Visit`<br/>... 156 more<br/>"]:::api
