%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Uianchorlayout["Uianchorlayout<br/>────────────<br/>+ `getAnchoredEdge`<br/>+ `getHookedEdge`<br/>+ `getHookedWidget`<br/>+ `getHookedPoint`<br/>+ `m_anchoredEdge`<br/>... 15 more<br/>"]:::api
