%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Uiboxlayout["Uiboxlayout<br/>────────────<br/>+ `applyStyle`<br/>+ `addWidget`<br/>+ `removeWidget`<br/>+ `setSpacing`<br/>+ `setFitChildren`<br/>... 3 more<br/>"]:::api
