%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Uihorizontallayout["Uihorizontallayout<br/>────────────<br/>+ applyStyle<br/>+ setAlignRight<br/>+ isUIHorizontalLayout<br/>+ internalUpdate<br/>+ m_alignChidren<br/>+ m_alignRight<br/>"]:::api
