%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Uilayout["Uilayout<br/>────────────<br/>+ update<br/>+ updateLater<br/>+ applyStyle<br/>+ addWidget<br/>+ removeWidget<br/>+ disableUpdates<br/>+ enableUpdates<br/>+ setParent<br/>+ getParentWidget<br/>+ isUpdateDisabled<br/>+ isUpdating<br/>+ isUIAnchorLayout<br/>+ isUIBoxLayout<br/>+ isUIHorizontalLayout<br/>+ isUIVerticalLayout<br/>+ isUIGridLayout<br/>+ internalUpdate<br/>+ m_updateDisabled<br/>+ m_updating<br/>+ m_updateScheduled<br/><i>(+ 1 more members)</i><br/>"]:::api
