%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Uimanager["Uimanager<br/>────────────<br/>+ init<br/>+ terminate<br/>+ render<br/>+ resize<br/>+ inputEvent<br/>+ updatePressedWidget<br/>+ updateDraggingWidget<br/>+ updateHoveredWidget<br/>+ clearStyles<br/>+ importStyle<br/>+ importStyleFromString<br/>+ importStyleFromOTML<br/>+ getStyle<br/>+ getStyleClass<br/>+ loadUIFromString<br/>+ loadUI<br/>+ displayUI<br/>+ createWidget<br/>+ createWidgetFromOTML<br/>+ setMouseReceiver<br/><i>(+ 16 more members)</i><br/>"]:::api
