%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Uitextedit["Uitextedit<br/>────────────<br/>+ `drawSelf`<br/>+ `setCursorPos`<br/>+ `setSelection`<br/>+ `setCursorVisible`<br/>+ `setTextHidden`<br/>... 59 more<br/>"]:::api
