%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Uitextedit {
        +drawSelf()
        +update()
        +setCursorPos()
        +setSelection()
        +setCursorVisible()
        +setTextHidden()
        +setValidCharacters()
        +setShiftNavigation()
        +setMultiline()
        +setMaxLength()
        +setTextVirtualOffset()
        +setEditable()
        +setSelectable()
        +setSelectionColor()
        +setSelectionBackgroundColor()
        +setAutoScroll()
        +setAutoSubmit()
        +setPlaceholder()
        +setPlaceholderColor()
        +setPlaceholderAlign()
        +setPlaceholderFont()
        +moveCursorHorizontally()
        +moveCursorVertically()
        +appendText()
        +appendCharacter()
        +removeCharacter()
        +blinkCursor()
        +del()
        +paste()
        +copy()
        +cut()
        +selectAll()
        +clearSelection()
        +wrapText()
        +getDisplayedText()
        +getSelection()
        +getTextPos()
        +getCursorPos()
        +getTextVirtualOffset()
        +getTextVirtualSize()
        +getTextTotalSize()
        +getMaxLength()
        +getSelectionStart()
        +getSelectionEnd()
        +getSelectionColor()
        +getSelectionBackgroundColor()
        +hasSelection()
        +isCursorVisible()
        +isTextHidden()
        +isShiftNavigation()
        +isMultiline()
        +isEditable()
        +isSelectable()
        +isAutoScrolling()
        +updateText()
        +disableUpdates()
        +enableUpdates()
        +recacheGlyphs()
        +onStyleApply()
        +onGeometryChange()
        +onFocusChange()
        +onKeyText()
        +onKeyPress()
        +onMousePress()
        +onMouseRelease()
        +onMouseMove()
        +onDoubleClick()
        +onTextAreaUpdate()
    }
