%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Uiverticallayout["Uiverticallayout<br/>────────────<br/>+ applyStyle<br/>+ setAlignBottom<br/>+ isAlignBottom<br/>+ isUIVerticalLayout<br/>+ internalUpdate<br/>+ m_alignBottom<br/>"]:::api
