%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Uiwidget {
        +set()
        +addChild()
        +onChildIdChange()
        +insertChild()
        +removeChild()
        +focusChild()
        +focusNextChild()
        +focusPreviousChild()
        +lowerChild()
        +raiseChild()
        +moveChildToIndex()
        +reorderChildren()
        +lockChild()
        +unlockChild()
        +mergeStyle()
        +applyStyle()
        +addAnchor()
        +removeAnchor()
        +fill()
        +centerIn()
        +breakAnchors()
        +updateParentLayout()
        +updateLayout()
        +lock()
        +unlock()
        +focus()
        +recursiveFocus()
        +lower()
        +raise()
        +grabMouse()
        +ungrabMouse()
        +grabKeyboard()
        +ungrabKeyboard()
        +bindRectToParent()
        +destroy()
        +destroyChildren()
        +setId()
        +setParent()
        +setLayout()
        +setRect()
        +setStyle()
        +setStyleFromNode()
        +setEnabled()
        +setVisible()
        +setAutoDraw()
        +setOn()
        +setChecked()
        +setFocusable()
        +setPhantom()
        +setDraggable()
        +setFixedSize()
        +setClipping()
        +setLastFocusReason()
        +setAutoFocusPolicy()
        +setAutoRepeatDelay()
        +setVirtualOffset()
        +isAnchored()
        +isChildLocked()
        +hasChild()
        +getChildIndex()
        +getPaddingRect()
        +getMarginRect()
        +getChildrenRect()
        +getAnchoredLayout()
        +getRootParent()
        +getChildAfter()
        +getChildBefore()
        +getChildById()
        +getChildByPos()
        +getChildByIndex()
        +recursiveGetChildById()
        +recursiveGetChildByPos()
        +recursiveGetChildren()
        +recursiveGetChildrenByPos()
        +recursiveGetChildrenByMarginPos()
        +backwardsGetWidgetById()
        +setState()
        +hasState()
        +internalDestroy()
        +updateState()
        +updateStates()
        +updateChildrenIndexStates()
        +updateStyle()
        +propagateOnKeyText()
        +propagateOnKeyDown()
        +propagateOnKeyPress()
        +propagateOnKeyUp()
        +propagateOnMouseEvent()
        +propagateOnMouseMove()
        +resize()
        +move()
        +rotate()
        +hide()
        +show()
        +disable()
        +enable()
        +isActive()
        +isEnabled()
        +isDisabled()
        +isFocused()
        +isHovered()
        +isPressed()
        +isFirst()
        +isMiddle()
        +isLast()
        +isAlternate()
        +isChecked()
        +isOn()
        +isDragging()
        +isVisible()
        +isHidden()
        +isExplicitlyEnabled()
        +isExplicitlyVisible()
        +isAutoDraw()
        +isFocusable()
        +isPhantom()
        +isDraggable()
        +isFixedSize()
        +isClipping()
        +isDestroyed()
        +hasChildren()
        +containsMarginPoint()
        +containsPaddingPoint()
        +containsPoint()
        +getId()
        +getSource()
        +getParent()
        +getParentId()
        +getFocusedChild()
        +getChildren()
        +getFirstChild()
        +getLastChild()
        +getLayout()
        +getStyle()
        +getChildCount()
        +getLastFocusReason()
        +getAutoFocusPolicy()
        +getAutoRepeatDelay()
        +getVirtualOffset()
        +getStyleName()
        +getLastClickPosition()
        +isRootChild()
        +setRootChild()
        +initBaseStyle()
        +parseBaseStyle()
        +drawBackground()
        +drawBorder()
        +drawIcon()
        +setX()
        +setY()
        +setWidth()
        +setHeight()
        +setSize()
        +setPosition()
        +setColor()
        +setBackgroundColor()
        +setBackgroundOffsetX()
        +setBackgroundOffsetY()
        +setBackgroundOffset()
        +setBackgroundWidth()
        +setBackgroundHeight()
        +setBackgroundSize()
        +setBackgroundRect()
        +setIcon()
        +setIconColor()
        +setIconOffsetX()
        +setIconOffsetY()
        +setIconOffset()
        +setIconWidth()
        +setIconHeight()
        +setIconSize()
        +setIconRect()
        +setIconClip()
        +setIconAlign()
        +setBorderWidth()
        +setBorderWidthTop()
        +setBorderWidthRight()
        +setBorderWidthBottom()
        +setBorderWidthLeft()
        +setBorderColor()
        +setBorderColorTop()
        +setBorderColorRight()
        +setBorderColorBottom()
        +setBorderColorLeft()
        +setMargin()
        +setMarginHorizontal()
        +setMarginVertical()
        +setMarginTop()
        +setMarginRight()
        +setMarginBottom()
        +setMarginLeft()
        +setPadding()
        +setPaddingHorizontal()
        +setPaddingVertical()
        +setPaddingTop()
        +setPaddingRight()
        +setPaddingBottom()
        +setPaddingLeft()
        +setOpacity()
        +setRotation()
        +setChangeCursorImage()
        +setCursor()
        +getX()
        +getY()
        +getPosition()
        +getWidth()
        +getHeight()
        +getSize()
        +getRect()
        +getColor()
        +getBackgroundColor()
        +getBackgroundOffsetX()
        +getBackgroundOffsetY()
        +getBackgroundOffset()
        +getBackgroundWidth()
        +getBackgroundHeight()
        +getBackgroundSize()
        +getBackgroundRect()
        +getIconColor()
        +getIconOffsetX()
        +getIconOffsetY()
        +getIconOffset()
        +getIconWidth()
        +getIconHeight()
        +getIconSize()
        +getIconRect()
        +getIconClip()
        +getIconPath()
        +getIconAlign()
        +getBorderTopColor()
        +getBorderRightColor()
        +getBorderBottomColor()
        +getBorderLeftColor()
        +getBorderTopWidth()
        +getBorderRightWidth()
        +getBorderBottomWidth()
        +getBorderLeftWidth()
        +getMarginTop()
        +getMarginRight()
        +getMarginBottom()
        +getMarginLeft()
        +getPaddingTop()
        +getPaddingRight()
        +getPaddingBottom()
        +getPaddingLeft()
        +getOpacity()
        +getRotation()
        +isChangingCursorImage()
        +initImage()
        +parseImageStyle()
        +updateImageCache()
        +configureBorderImage()
        +drawImage()
        +setQRCode()
        +setImageSource()
        +setImageSourceBase64()
        +setImageClip()
        +setImageOffsetX()
        +setImageOffsetY()
        +setImageOffset()
        +setImageWidth()
        +setImageHeight()
        +setImageSize()
        +setImageRect()
        +setImageColor()
        +setImageFixedRatio()
        +setImageRepeated()
        +setImageSmooth()
        +setImageAutoResize()
        +setImageBorderTop()
        +setImageBorderRight()
        +setImageBorderBottom()
        +setImageBorderLeft()
        +setImageBorder()
        +setImageShader()
        +getImageClip()
        +getImageOffsetX()
        +getImageOffsetY()
        +getImageOffset()
        +getImageWidth()
        +getImageHeight()
        +getImageSize()
        +getImageRect()
        +getImageColor()
        +isImageFixedRatio()
        +isImageSmooth()
        +isImageAutoResize()
        +getImageBorderTop()
        +getImageBorderRight()
        +getImageBorderBottom()
        +getImageBorderLeft()
        +getImageTextureWidth()
        +getImageTextureHeight()
        +getImageShader()
        +initText()
        +parseTextStyle()
        +drawText()
        +resizeToText()
        +clearText()
        +setText()
        +setColoredText()
        +setTextAlign()
        +setTextOffset()
        +setTextWrap()
        +setTextAutoResize()
        +setTextHorizontalAutoResize()
        +setTextVerticalAutoResize()
        +setTextOnlyUpperCase()
        +setFont()
        +setShadow()
        +getText()
        +getDrawText()
        +getTextAlign()
        +getTextOffset()
        +getTextWrap()
        +getFont()
        +getTextSize()
        +draw()
        +drawSelf()
        +drawChildren()
        +m_id()
        +m_source()
        +m_rect()
        +m_virtualOffset()
        +m_autoDraw()
        +m_enabled()
        +m_visible()
        +m_focusable()
        +m_fixedSize()
        +m_phantom()
        +m_draggable()
        +m_destroyed()
        +m_clipping()
        +m_layout()
        +m_parent()
        +m_parentId()
        +m_children()
        +m_lockedChildren()
        +m_childrenShortcuts()
        +m_focusedChild()
        +m_style()
        +m_clickTimer()
        +m_lastFocusReason()
        +m_autoFocusPolicy()
        +onStyleApply()
        +onGeometryChange()
        +onLayoutUpdate()
        +onFocusChange()
        +onChildFocusChange()
        +onHoverChange()
        +onVisibilityChange()
        +onDragEnter()
        +onDragLeave()
        +onDragMove()
        +onDrop()
        +onKeyText()
        +onKeyDown()
        +onKeyPress()
        +onKeyUp()
        +onMousePress()
        +onMouseRelease()
        +onMouseMove()
        +onMouseWheel()
        +onClick()
        +onDoubleClick()
        +m_isRootChild()
        +m_color()
        +m_backgroundColor()
        +m_backgroundRect()
        +m_icon()
        +m_iconColor()
        +m_iconRect()
        +m_iconClipRect()
        +m_iconPath()
        +m_iconAlign()
        +m_borderColor()
        +m_borderWidth()
        +m_margin()
        +m_padding()
        +m_opacity()
        +m_rotation()
        +m_autoRepeatDelay()
        +m_lastClickPosition()
        +m_imageTexture()
        +m_imageClipRect()
        +m_imageRect()
        +m_imageColor()
        +m_iconOffset()
        +m_imageFixedRatio()
        +m_imageRepeated()
        +m_imageSmooth()
        +m_imageAutoResize()
        +m_imageBorder()
        +m_shader()
        +updateText()
        +onTextChange()
        +onFontChange()
        +m_text()
        +m_drawText()
        +m_textAlign()
        +m_textOffset()
        +m_textWrap()
        +m_textVerticalAutoResize()
        +m_textHorizontalAutoResize()
        +m_textOnlyUpperCase()
        +m_font()
        +m_shadow()
    }
