%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Uiwidget {
        +set
        +addChild
        +onChildIdChange
        +insertChild
        +removeChild
        +focusChild
        +focusNextChild
        +focusPreviousChild
        +lowerChild
        +raiseChild
        +... (307 more methods)
    }
