%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Vertexarray {
        +addVertex
        +addTriangle
        +addRect
        +addRect
        +addQuad
        +addUpsideDownQuad
        +clear
        +vertexCount
        +size
        +cache
        +... (1 more methods)
    }
