%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    Vertexarray["Vertexarray<br/>────────────<br/>+ m_hardwareBuffer<br/>+ addVertex<br/>+ addTriangle<br/>+ addRect<br/>+ top<br/>+ right<br/>+ bottom<br/>+ left<br/>+ addRect<br/>+ top<br/>+ right<br/>+ bottom<br/>+ left<br/>+ addQuad<br/>+ top<br/>+ right<br/>+ bottom<br/>+ left<br/>+ addUpsideDownQuad<br/>+ top<br/><i>(+ 8 more members)</i><br/>"]:::api
