%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Win32Window {
        +internalSetupTimerAccuracy
        +internalCreateWindow
        +internalCreateGLContext
        +internalDestroyGLContext
        +internalRestoreGLContext
        +isExtensionSupported
        +windowProc
        +dispatcherWindowProc
        +retranslateVirtualKey
        +init
        +... (28 more methods)
    }
