%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class Win32Window {
        +internalSetupTimerAccuracy()
        +internalCreateWindow()
        +internalCreateGLContext()
        +internalDestroyGLContext()
        +internalRestoreGLContext()
        +isExtensionSupported()
        +windowProc()
        +dispatcherWindowProc()
        +retranslateVirtualKey()
        +init()
        +terminate()
        +move()
        +resize()
        +show()
        +hide()
        +minimize()
        +maximize()
        +poll()
        +swapBuffers()
        +showMouse()
        +hideMouse()
        +displayFatalError()
        +setMouseCursor()
        +restoreMouseCursor()
        +setTitle()
        +setMinimumSize()
        +setFullscreen()
        +setVerticalSync()
        +setIcon()
        +setClipboardText()
        +getDisplaySize()
        +getClipboardText()
        +getPlatformType()
        +flash()
        +internalLoadMouseCursor()
        +getClientRect()
        +getWindowRect()
        +adjustWindowRect()
    }
