%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class X11Window {
        +internalOpenDisplay()
        +internalCreateWindow()
        +internalSetupWindowInput()
        +internalCheckGL()
        +internalChooseGLVisual()
        +internalCreateGLContext()
        +internalDestroyGLContext()
        +internalConnectGLContext()
        +isExtensionSupported()
        +init()
        +terminate()
        +move()
        +resize()
        +show()
        +hide()
        +minimize()
        +maximize()
        +poll()
        +swapBuffers()
        +showMouse()
        +hideMouse()
        +setMouseCursor()
        +restoreMouseCursor()
        +setTitle()
        +setMinimumSize()
        +setFullscreen()
        +setVerticalSync()
        +setIcon()
        +setClipboardText()
        +getDisplaySize()
        +getClipboardText()
        +getPlatformType()
        +displayFatalError()
        +internalLoadMouseCursor()
    }
