%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'}, 'securityLevel':'loose'}}%%
graph TD
    classDef api fill:#3498db,stroke:#fff,color:#fff;
    
    X11Window["X11Window<br/>────────────<br/>+ init<br/>+ terminate<br/>+ move<br/>+ resize<br/>+ show<br/>+ hide<br/>+ minimize<br/>+ maximize<br/>+ poll<br/>+ swapBuffers<br/>+ showMouse<br/>+ hideMouse<br/>+ setMouseCursor<br/>+ restoreMouseCursor<br/>+ setTitle<br/>+ setMinimumSize<br/>+ setFullscreen<br/>+ setVerticalSync<br/>+ setIcon<br/>+ setClipboardText<br/><i>(+ 5 more members)</i><br/>"]:::api
