%%{init: {'theme':'dark','themeVariables': {'primaryTextColor':'#ddd','lineColor':'#9aa0a6'},'securityLevel':'loose'}}%%
classDiagram
    class X11Window {
        +internalOpenDisplay
        +internalCreateWindow
        +internalSetupWindowInput
        +internalCheckGL
        +internalChooseGLVisual
        +internalCreateGLContext
        +internalDestroyGLContext
        +internalConnectGLContext
        +isExtensionSupported
        +init
        +... (24 more methods)
    }
