name: Android SDK setup (fix)

on:
  workflow_dispatch:

jobs:
  android-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Android cmdline-tools
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true

      - name: Install required Android packages (API 25 + NDK r21d + CMake)
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install \
            "platforms;android-25" \
            "build-tools;34.0.0" \
            "ndk;21.4.7075529" \
            "cmake;3.22.1"
