name: Android build (CMake)

on:
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (z LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Android cmdline-tools + pakiety
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true

      - name: Zainstaluj pakiety SDK/NDK/CMake
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platforms;android-25"
          sdkmanager --install "build-tools;34.0.0"
          sdkmanager --install "ndk;21.4.7075529"
          sdkmanager --install "cmake;3.22.1"

      - name: Narzędzia systemowe
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build p7zip-full

      - name: Ustaw ścieżki NDK
        run: |
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/21.4.7075529" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/21.4.7075529" >> $GITHUB_ENV

      - name: Rozpakuj prebuilt android_libs.7z
        run: |
          set -e
          if [ ! -f "android/android_libs.7z" ]; then
            echo "::error::Brakuje pliku android/android_libs.7z w repo (prekompilowane biblioteki na Androida)."
            exit 1
          fi
          7z x android/android_libs.7z -oandroid/android_libs
          echo "== Zawartość android/android_libs =="
          find android/android_libs -maxdepth 2 -type d -print | sed 's/^/  /'

      - name: Ustal ścieżki android_libs (INC/LIB)
        run: |
          set -e
          ROOT="$GITHUB_WORKSPACE/android/android_libs"

          # domyślne + fallback (niektóre paczki nie mają podkatalogów arch)
          INC="$ROOT/arm64-v8a/include"; [ -d "$INC" ] || INC="$ROOT/include"
          LIB="$ROOT/arm64-v8a/lib";     [ -d "$LIB" ] || LIB="$ROOT/lib"

          echo "INC=$INC"          | tee -a $GITHUB_ENV
          echo "LIB=$LIB"          | tee -a $GITHUB_ENV
          echo "BOOST_LIBDIR=$LIB" | tee -a $GITHUB_ENV

          # LuaJIT nagłówki bywają w luajit-2.0/
          LUAJIT_INC="$INC"; [ -d "$INC/luajit-2.0" ] && LUAJIT_INC="$INC/luajit-2.0"
          echo "LUAJIT_INC=$LUAJIT_INC" | tee -a $GITHUB_ENV
          echo "LUAJIT_LIB=$LIB"        | tee -a $GITHUB_ENV

          echo "== sanity-check =="
          test -d "$INC/boost"          || (echo "::error::Brak nagłówków Boost w $INC/boost" && exit 1)
          test -f "$LIB/libzip.a"       || (echo "::error::Brak $LIB/libzip.a" && exit 1)
          test -f "$LIB/libbz2.a"       || (echo "::error::Brak $LIB/libbz2.a" && exit 1)
          test -f "$LIB/libluajit.a"    || (echo "::error::Brak $LIB/libluajit.a" && exit 1)
          test -f "$INC/zipconf.h"      || (echo "::error::Brak $INC/zipconf.h" && exit 1)

      - name: Configure (arm64-v8a)
        run: |
          set -e
          ROOT="$GITHUB_WORKSPACE/android/android_libs"

          # Ścieżki do GLESv2/EGL z NDK (Android używa OpenGL ES + EGL, nie GL/GLX)
          GLINC="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include"
          GLLIBDIR="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android"
          GLESV2="$GLLIBDIR/libGLESv2.so"
          EGL="$GLLIBDIR/libEGL.so"

          ls -l "$GLESV2" "$EGL" "$GLINC" || { echo "::error::Brak GLES/EGL w NDK"; exit 1; }

          cmake -S . -B build-android-arm64 -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake" \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-25 \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
            \
            -DBOOST_ROOT="$ROOT" \
            -DBOOST_INCLUDEDIR="$INC" \
            -DBOOST_LIBRARYDIR="$BOOST_LIBDIR" \
            \
            -DBZIP2_INCLUDE_DIR="$INC" \
            -DBZIP2_LIBRARIES="$LIB/libbz2.a" \
            \
            -DLIBZIP_INCLUDE_DIR_ZIP="$INC" \
            -DLIBZIP_INCLUDE_DIR_ZIPCONF="$INC" \
            -DLIBZIP_LIBRARY="$LIB/libzip.a" \
            \
            -DLUAJIT_INCLUDE_DIR="$LUAJIT_INC" \
            -DLUAJIT_LIBRARY="$LUAJIT_LIB/libluajit.a" \
            \
            -DCMAKE_FIND_ROOT_PATH="$ROOT" \
            -DCMAKE_PREFIX_PATH="$ROOT" \
            \
            -DUSE_OPENGL_ES=ON \
            -DOPENGL_ES=ON \
            -DOPENGL_INCLUDE_DIR="$GLINC" \
            -DOPENGL_opengl_LIBRARY="$GLESV2" \
            -DOPENGL_glx_LIBRARY="$EGL" \
            -DOPENGL_egl_LIBRARY="$EGL"

      - name: Build (arm64-v8a)
        run: cmake --build build-android-arm64 -j 4

      - name: Upload artefakt (build-android-arm64)
        uses: actions/upload-artifact@v4
        with:
          name: build-android-arm64
          path: build-android-arm64/**
