name: Android build (CMake)

on:
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Android cmdline-tools + pakiety
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true

      - name: Zainstaluj wymagane pakiety SDK/NDK/CMake
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install \
            "platforms;android-25" \
            "build-tools;34.0.0" \
            "ndk;21.4.7075529" \
            "cmake;3.22.1"

      - name: Narzędzia do builda
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: Ustaw ścieżki NDK
        run: |
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/21.4.7075529" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/21.4.7075529" >> $GITHUB_ENV

      - name: Configure (arm64-v8a)
        run: |
          cmake -S . -B build-android-arm64 -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake" \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-25 \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5

      - name: Build (arm64-v8a)
        run: cmake --build build-android-arm64 -j 4

      - name: Configure (armeabi-v7a)
        run: |
          cmake -S . -B build-android-armv7 -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake" \
            -DANDROID_ABI=armeabi-v7a \
            -DANDROID_PLATFORM=android-25 \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5

      - name: Build (armeabi-v7a)
        run: cmake --build build-android-armv7 -j 4

      - name: (Opcjonalnie) dołącz assets/data.zip
        if: ${{ hashFiles('android/otclientv8/assets/data.zip') != '' }}
        run: |
          mkdir -p artifacts/assets
          cp android/otclientv8/assets/data.zip artifacts/assets/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: |
            build-android-arm64/**
            build-android-armv7/**
            artifacts/**
