name: Android build (CMake)

on:
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (z LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Android cmdline-tools + pakiety
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true

      - name: Zainstaluj SDK/NDK/CMake
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install \
            "platforms;android-25" \
            "build-tools;34.0.0" \
            "ndk;21.4.7075529" \
            "cmake;3.22.1"

      - name: Narzędzia systemowe
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build p7zip-full

      - name: Ustaw ścieżki NDK
        run: |
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/21.4.7075529" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/21.4.7075529" >> $GITHUB_ENV

      - name: Ustal INC/LIB (auto-detekcja) + sanity-check
        run: |
          set -e
          ROOT="$GITHUB_WORKSPACE/android/android_libs"
          INC="$ROOT/include"
          [ -d "$INC" ] || { echo "::error::Brak katalogu include ($INC)"; exit 1; }
          if   [ -d "$ROOT/lib" ];   then LIB="$ROOT/lib"
          elif [ -d "$ROOT/lib64" ]; then LIB="$ROOT/lib64"
          else echo "::error::Brak katalogu lib/lib64 w $ROOT"; exit 1
          fi
          echo "INC=$INC"          | tee -a $GITHUB_ENV
          echo "LIB=$LIB"          | tee -a $GITHUB_ENV
          echo "BOOST_LIBDIR=$LIB" | tee -a $GITHUB_ENV
          LUAJIT_INC="$INC"; [ -d "$INC/luajit-2.0" ] && LUAJIT_INC="$INC/luajit-2.0"
          echo "LUAJIT_INC=$LUAJIT_INC" | tee -a $GITHUB_ENV
          echo "LUAJIT_LIB=$LIB"        | tee -a $GITHUB_ENV
          echo "== sanity-check =="
          test -d "$INC/boost"       || (echo "::error::Brak nagłówków Boost w $INC/boost" && exit 1)
          test -f "$LIB/libzip.a"    || (echo "::error::Brak $LIB/libzip.a" && exit 1)
          test -f "$LIB/libbz2.a"    || (echo "::error::Brak $LIB/libbz2.a" && exit 1)
          test -f "$LIB/libluajit.a" || (echo "::error::Brak $LIB/libluajit.a" && exit 1)
          test -f "$INC/zipconf.h"   || (echo "::error::Brak $INC/zipconf.h" && exit 1)

      - name: (Android/GLES) Atrapowy GLEW (header + lib)
        run: |
          set -e
          STUB="$GITHUB_WORKSPACE/android/glew_stub"
          mkdir -p "$STUB/include/GL" "$STUB/lib"
          cat > "$STUB/include/GL/glew.h" <<'EOF'
          #pragma once
          /* Minimalny stub GLEW dla buildu na Android/GLES */
          static inline int __glew_dummy(void){return 0;}
          EOF
          printf "int __glew_stub = 0;\n" > "$STUB/stub.c"
          cc -c -o "$STUB/stub.o" "$STUB/stub.c"
          ar rcs "$STUB/lib/libGLEW.a" "$STUB/stub.o"
          rm -f "$STUB/stub.c" "$STUB/stub.o"
          echo "GLEW_INCLUDE_DIR=$STUB/include" >> $GITHUB_ENV
          echo "GLEW_LIBRARY=$STUB/lib/libGLEW.a" >> $GITHUB_ENV

      - name: Debug GLEW stub
        run: |
          ls -l $GLEW_INCLUDE_DIR/GL/glew.h
          ls -l $GLEW_LIBRARY

      - name: Configure (arm64-v8a)
        run: |
          set -e
          ROOT="$GITHUB_WORKSPACE/android/android_libs"
          GLINC="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include"
          GLESV2="$ANDROID_NDK_ROOT/platforms/android-24/arch-arm64/usr/lib/libGLESv2.so"
          EGL="$ANDROID_NDK_ROOT/platforms/android-24/arch-arm64/usr/lib/libEGL.so"
          ls -l "$GLESV2" "$EGL" "$GLINC"
          cmake -S . -B build-android-arm64 -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake" \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-25 \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
            \
            -DBOOST_ROOT="$ROOT" \
            -DBOOST_INCLUDEDIR="$INC" \
            -DBOOST_LIBRARYDIR="$BOOST_LIBDIR" \
            \
            -DBZIP2_INCLUDE_DIR="$INC" \
            -DBZIP2_LIBRARIES="$LIB/libbz2.a" \
            \
            -DLIBZIP_INCLUDE_DIR_ZIP="$INC" \
            -DLIBZIP_INCLUDE_DIR_ZIPCONF="$INC" \
            -DLIBZIP_LIBRARY="$LIB/libzip.a" \
            \
            -DLUAJIT_INCLUDE_DIR="$LUAJIT_INC" \
            -DLUAJIT_LIBRARY="$LUAJIT_LIB/libluajit.a" \
            \
            -DCMAKE_FIND_ROOT_PATH="$ROOT" \
            -DCMAKE_PREFIX_PATH="$ROOT" \
            \
            -DUSE_OPENGL_ES=ON \
            -DOPENGL_ES=ON \
            -DOPENGL_INCLUDE_DIR="$GLINC" \
            -DOPENGL_opengl_LIBRARY="$GLESV2" \
            -DOPENGL_glx_LIBRARY="$EGL" \
            -DOPENGL_egl_LIBRARY="$EGL" \
            \
            -DGLEW_INCLUDE_DIR="$GLEW_INCLUDE_DIR" \
            -DGLEW_LIBRARY="$GLEW_LIBRARY"

      - name: Build (arm64-v8a)
        run: cmake --build build-android-arm64 -j 4

      - name: Upload artefaktów (wyniki buildu)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-android-arm64
          path: |
            build-android-arm64/**
            !**/*.obj
            !**/*.o
