name: API + Exports
on:
  workflow_dispatch: {}        # tylko ręcznie

permissions:
  contents: write

concurrency:
  group: api-exports-manual
  cancel-in-progress: false    # nie zabijaj w trakcie

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with: { node-version: "20" }

      - run: npm i glob js-yaml --no-save
      - run: node scripts/extract-api.mjs
      - run: node scripts/concat-md.mjs mkdocs.yml OTCv8-Docs.md
      - run: node scripts/normalize-md.mjs OTCv8-Docs.md

      - uses: actions/setup-python@v5
        with: { python-version: "3.x" }
      - run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-macros-plugin mkdocs-git-revision-date-localized-plugin
      - run: mkdocs build

      - run: |
          sudo apt-get update && sudo apt-get install -y pandoc zip
          mkdir -p docs/downloads
          pandoc OTCv8-Docs.md -f gfm+hard_line_breaks-raw_html -t docx -o docs/downloads/OTCv8-Docs.docx --wrap=none
          pandoc OTCv8-Docs.md -f gfm+hard_line_breaks-raw_html -t epub -o docs/downloads/OTCv8-Docs.epub --toc --wrap=none
          zip -r docs/downloads/site.zip site
          ls -lh docs/downloads

      - name: Commit artefaktów (bez odpalania innych CI)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -f docs/api/otcv8-full-api.md docs/downloads/*
          git commit -m "[skip ci] docs: auto API + exports" || echo "no changes"
          git push
