- name: Ensure vcpkg.json (temporary if missing)
  shell: bash
  run: |
    if [ ! -f vcpkg.json ]; then
      printf '%s\n' \
      '{' \
      '  "name": "otclient-v8",' \
      '  "version-string": "0.1.0-ci",' \
      '  "dependencies": [' \
      '    "sdl2",' \
      '    "openal-soft",' \
      '    "physfs",' \
      '    "libpng",' \
      '    "zlib",' \
      '    "brotli",' \
      '    "lz4",' \
      '    "openssl",' \
      '    "freetype"' \
      '  ]' \
      '}' > vcpkg.json
      echo "Created TEMP vcpkg.json (consider committing a proper one to repo)."
    fi
