name: Deploy Modules (only)

on:
  push:
    branches: [ master ]
    paths:
      - 'docs/modules/**'
      - 'mkdocs.modules.yml'
      - '.github/workflows/docs-modules-deploy.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: docs-pages-modules
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-modules-only-${{ runner.os }}-${{ hashFiles('mkdocs.modules.yml') }}
          restore-keys: |
            pip-modules-only-${{ runner.os }}-

      - name: Install deps (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install \
            "mkdocs==1.6.1" \
            "mkdocs-material==9.5.49" \
            mkdocs-glightbox \
            mkdocs-macros-plugin \
            mkdocs-git-revision-date-localized-plugin \
            pymdown-extensions

      - name: Show versions
        run: |
          python --version
          mkdocs --version
          python - << 'PY'
          import pkgutil, sys
          wanted = ["mkdocs", "mkdocs_material", "mkdocs_glightbox",
                    "mkdocs_macros_plugin",
                    "mkdocs_git_revision_date_localized_plugin",
                    "pymdown_extensions"]
          for w in wanted:
              print(w, "=>", pkgutil.find_loader(w) is not None)
          PY

      - name: Build site (modules only)
        run: |
          set -euo pipefail
          mkdocs build --clean -f mkdocs.modules.yml -v

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
