name: Build & Deploy Docs (via GitHub Actions)

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1) Najpierw utwórz plik z zależnościami
      - name: Write requirements
        run: |
          mkdir -p .github
          cat > .github/mkdocs-requirements.txt <<'EOF'
          mkdocs==1.6.1
          mkdocs-material==9.5.34
          mkdocs-exclude
          mkdocs-redirects
          mkdocs-git-revision-date-localized-plugin
          EOF

      # 2) Dopiero teraz setup Pythona z cache, bo plik już istnieje
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: .github/mkdocs-requirements.txt

      - name: Install deps
        run: pip install -r .github/mkdocs-requirements.txt

      - name: Build FULL (mkdocs.yml)
        env:
          GITHUB_PAGES: true
        run: |
          mkdocs --version
          mkdocs build --clean -v

      - name: Build MODULES (mkdocs.modules.yml) if present
        if: ${{ hashFiles('mkdocs.modules.yml') != '' }}
        run: |
          mkdocs build --clean -f mkdocs.modules.yml -v --site-dir site-modules
          mkdir -p site/modules-preview
          rsync -a site-modules/ site/modules-preview/

      - name: Prepare Pages artifact
        run: |
          touch site/.nojekyll
          [ -f site/index.html ] || echo "<meta http-equiv='refresh' content='0; url=./'>" > site/index.html

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
