name: Docs

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Jeśli koniecznie chcesz limit: zwiększ go, np. 60 minut. Możesz też to pole skasować.
    timeout-minutes: 60

    steps:
      - name: Checkout (pełna historia – ważne dla dat z gita)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs==1.6.1 mkdocs-material mkdocs-glightbox \
                     mkdocs-macros-plugin mkdocs-redirects \
                     mkdocs-git-revision-date-localized-plugin

      - name: Make build script executable
        run: chmod +x scripts/ci-build.sh

      - name: Build site (keep-alive + log)
        run: ./scripts/ci-build.sh

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true
