name: Build & Deploy Docs
on:
  push:
    branches: [ master, main ]
    paths:
      - 'docs/**'
      - 'data/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r docs/requirements.txt
      - name: Prepare data → docs/_static/data
        run: |
          if [ -d "data" ]; then
            mkdir -p docs/_static/data
            rsync -a --delete data/ docs/_static/data/
          fi
      - name: Build HTML
        run: sphinx-build -b html docs docs/_build/html
      - name: Build JSON (RAG)
        continue-on-error: true
        run: |
          sphinx-build -b json docs docs/_build/json || {
            echo "::warning::JSON build failed - this is a known issue with PyData theme"
            echo "HTML documentation will still be published"
          }
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: |
            docs/_build/html
            docs/_build/json
      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_build/html
          force_orphan: true
