name: Build & Deploy Docs

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install \
            mkdocs==1.6.1 \
            mkdocs-material==9.5.34 \
            mkdocs-exclude \
            mkdocs-redirects \
            mkdocs-git-revision-date-localized-plugin

      - name: Build FULL (mkdocs.yml)
        run: |
          mkdocs --version
          mkdocs build --clean -v

      - name: Build MODULES (mkdocs.modules.yml)
        run: |
          mkdocs build --clean -f mkdocs.modules.yml -v

      - name: Prepare gh-pages structure
        run: |
          rm -rf gh-pages && mkdir -p gh-pages
          # root = pełny serwis
          rsync -a site/ gh-pages/
          # /modules-preview/ = tylko moduły
          mkdir -p gh-pages/modules-preview
          rsync -a site-modules/ gh-pages/modules-preview/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
          publish_branch: gh-pages
