name: Build & Deploy docs

on:
  push:
    branches: [ master ]
    paths:
      - 'mkdocs.yml'
      - 'docs/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: docs-pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('mkdocs.yml') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install \
            mkdocs==1.6.1 \
            "mkdocs-material==9.5.49" \
            "mkdocs-material[imaging]" \
            mkdocs-glightbox \
            mkdocs-macros-plugin \
            mkdocs-git-revision-date-localized-plugin \
            mkdocs-redirects \
            mkdocs-exclude \
            "pymdown-extensions==10.8.1"

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Build site (keep-alive + log)
        shell: bash
        env:
          GITHUB_PAGES: true
        run: |
          ( while true; do echo "[keep-alive] $(date -u +%H:%M:%S)"; sleep 30; done ) &
          KEEPALIVE_PID=$!
          set -o pipefail
          mkdocs --version
          mkdocs build --clean -v 2>&1 | tee build.log || STATUS=$?
          kill $KEEPALIVE_PID || true
          if [ -n "$STATUS" ]; then
            echo "::group::Last 200 lines of build.log"
            tail -n 200 build.log || true
            echo "::endgroup::"
            exit $STATUS
          fi

      - name: Upload build log (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: mkdocs-build-log
          path: build.log
          retention-days: 7

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
