name: Docs rebuild (manual)

on:
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs & plugins
        run: |
          python -m pip install --upgrade pip
          pip install \
            mkdocs mkdocs-material mkdocs-glightbox \
            mkdocs-macros-plugin mkdocs-git-revision-date-localized-plugin \
            mkdocs-with-pdf

      - name: Build MkDocs site
        run: mkdocs build -d site

      - name: Assemble single markdown (OTCv8-Docs.md)
        run: |
          printf "# OTCv8 Docs (export)\n\n" > OTCv8-Docs.md
          git ls-files 'docs/**/*.md' | sort | while read f; do
            echo -e "\n\n---\n\n<!-- $f -->\n" >> OTCv8-Docs.md
            cat "$f" >> OTCv8-Docs.md
          done
          mkdir -p site/downloads
          cp OTCv8-Docs.md site/downloads/

      - name: Install pandoc & zip
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc zip

      - name: Export DOCX/EPUB/PDF
        run: |
          pandoc OTCv8-Docs.md -f gfm+hard_line_breaks-raw_html -t docx -o site/downloads/OTCv8-Docs.docx --wrap=none
          pandoc OTCv8-Docs.md -f gfm+hard_line_breaks-raw_html -t epub -o site/downloads/OTCv8-Docs.epub --toc --wrap=none
          # PDF (opcjonalnie – jeśli padnie LaTeX, zostanie pominięte)
          sudo apt-get install -y texlive-xetex fonts-dejavu || true
          pandoc OTCv8-Docs.md -o site/downloads/OTCv8-Docs.pdf --pdf-engine=xelatex -V geometry:margin=1in || true
          (cd site && zip -r downloads/site.zip .)

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
