name: docs
on:
  push:
    branches: [ master ]
    paths:
      - "docs/**"
      - "api/**"
      - ".github/workflows/docs.yml"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build docs
        run: |
          sphinx-build -b html docs docs/_build/html
      - name: Upload pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
