name: Build & Deploy MkDocs

on:
  push:
    branches: [ master ]
  workflow_dispatch:

# NIE anuluje trwającego runa gdy zrobisz kolejny push (eliminuje SIGTERM/143)
concurrency:
  group: mkdocs-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # cały job może trwać do 60 min

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install MkDocs + plugins
        run: |
          python -m pip install --upgrade pip
          pip install \
            mkdocs \
            mkdocs-material \
            mkdocs-glightbox \
            mkdocs-macros-plugin \
            mkdocs-git-revision-date-localized-plugin \
            mkdocs-redirects

      - name: Build site
        timeout-minutes: 55  # sam krok build ma długi limit
        run: |
          mkdocs build --clean -v

      - name: Upload build log and site (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mkdocs-site
          path: |
            site
            build.log
          if-no-files-found: ignore

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          # publish_branch: gh-pages  # odkomentuj, jeśli masz inną nazwę niż domyślna
