name: Build & Deploy Docs

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

# nie ubijamy poprzedniego builda przy kolejnym pushu
concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Write requirements (for cache)
        run: |
          mkdir -p .github
          cat > .github/mkdocs-requirements.txt <<'EOF'
          mkdocs==1.6.1
          mkdocs-material==9.5.34
          mkdocs-redirects
          mkdocs-exclude
          mkdocs-git-revision-date-localized-plugin
          EOF

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: .github/mkdocs-requirements.txt

      - name: Install deps
        run: pip install -r .github/mkdocs-requirements.txt

      - name: Build site (mkdocs.yml)
        env:
          GITHUB_PAGES: "true"
          ENABLE_GIT_DATES: "0"   # zmień na "1" jeśli chcesz daty commitów
        run: |
          mkdocs --version
          time mkdocs build --clean -v

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
