name: Deploy Modules (only)

on:
  push:
    branches: [ master ]
    paths:
      - 'mkdocs.modules.yml'
      - 'scripts/mkdocs_modules_hook.py'
      - 'docs/modules/**'
      - '.github/workflows/modules.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-modules
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install \
            mkdocs==1.6.1 \
            mkdocs-material==9.5.49 \
            "mkdocs-material[imaging]" \
            mkdocs-glightbox \
            mkdocs-macros-plugin \
            mkdocs-git-revision-date-localized-plugin \
            pymdown-extensions

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Build (modules only)
        run: |
          set -euo pipefail
          mkdocs --version
          mkdocs build --clean -f mkdocs.modules.yml -v

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
