name: Exports (DOCX/EPUB/ZIP)
on:
  push: { branches: [ master ] }
  workflow_dispatch: {}
permissions: { contents: write }

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # Zbuduj stronę -> site/
      - uses: actions/setup-python@v5
        with: { python-version: "3.x" }
      - run: python -m pip install --upgrade pip
      - run: pip install mkdocs mkdocs-material mkdocs-glightbox mkdocs-macros-plugin mkdocs-git-revision-date-localized-plugin
      - run: mkdocs build

      # Scal markdown wg nav -> plik w KORZENIU repo (łatwo zamontować)
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm i js-yaml glob
      - run: node scripts/concat-md.mjs mkdocs.yml OTCv8-Docs.md
      - run: mkdir -p docs/downloads && ls -lh . && test -f OTCv8-Docs.md

      # DOCX/EPUB lokalnym pandoc (bez PDF – stabilnie)
      - run: |
          sudo apt-get update
          sudo apt-get install -y pandoc zip
          pandoc OTCv8-Docs.md -o docs/downloads/OTCv8-Docs.docx
          pandoc OTCv8-Docs.md -o docs/downloads/OTCv8-Docs.epub --toc

      # ZIP całego site/
      - run: zip -r docs/downloads/site.zip site

      # Commit plików do Pages
      - name: Commit downloads
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/downloads/OTCv8-Docs.docx docs/downloads/OTCv8-Docs.epub docs/downloads/site.zip
          git commit -m "export: DOCX/EPUB/ZIP" || echo "no changes"
          git push
