name: Exports (DOCX/EPUB/ZIP)
on:
  push: { branches: [ master ] }
  workflow_dispatch: {}
permissions:
  contents: write
concurrency:
  group: exports-${{ github.ref }}
  cancel-in-progress: true

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # 1) Zbuduj scalony MD i stronÄ™
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm install js-yaml glob --no-save
      - run: node scripts/concat-md.mjs mkdocs.yml OTCv8-Docs.md

      - uses: actions/setup-python@v5
        with: { python-version: "3.x" }
      - run: python -m pip install --upgrade pip
      - run: |
          pip install \
            mkdocs \
            mkdocs-material \
            mkdocs-glightbox \
            mkdocs-macros-plugin \
            mkdocs-git-revision-date-localized-plugin
      - run: mkdocs build

      # 2) Eksporty
      - run: |
          sudo apt-get update && sudo apt-get install -y pandoc zip
          mkdir -p docs/downloads
          pandoc OTCv8-Docs.md -o docs/downloads/OTCv8-Docs.docx
          pandoc OTCv8-Docs.md -o docs/downloads/OTCv8-Docs.epub --toc
          zip -r docs/downloads/site.zip site
          ls -lh docs/downloads

      # 3) Commit TYLKO artefaktĂłw (bez workflowĂłw) + twardy reset do origin/master
      - name: Commit downloads (clean, no-workflows)
        shell: bash
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          # wyzeruj lokalny stan na zdalnym, ĹĽeby nie byĹ‚o "unstaged changes"
          git fetch origin master
          git reset --hard origin/master
          git clean -fd

          # dodaj WYĹÄ„CZNIE pliki z downloads
          git add -f docs/downloads/OTCv8-Docs.docx docs/downloads/OTCv8-Docs.epub docs/downloads/site.zip

          # sanity: upewnij siÄ™, ĹĽe nie ma zmian w .github/workflows
          if ! git diff --cached --name-only | grep -v '^.github/workflows/' >/dev/null; then
            echo "OK: brak zmian w workflowach"
          fi

          git commit -m "export: DOCX/EPUB/ZIP" || echo "no changes"
          git push

