name: Fix Markdown
on:
  push: { branches: [ master ] }
  workflow_dispatch: {}
permissions: { contents: write }
jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm i prettier markdownlint-cli@0 glob@10
      - run: node scripts/fix-md.mjs
      - run: npx prettier --write "docs/**/*.md"
      - run: npx markdownlint --fix "docs/**/*.md" || true
      - name: Commit fixes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/**/*.md
          git commit -m "chore(md): auto-fix formatting" || echo "no changes"
          git push
