%%{init: { 'theme': 'neutral', 'themeVariables': { 'primaryTextColor': '#ddd', 'lineColor': '#9aa0a6' } }}%%
graph TD
    A[03_modules.modules_graph] --> B[Dataset]
    B --> C[Page]

click A "./index.html#facet-03_modules.modules_graph" "Open modules_graph"
click ModulesGraph "./index.html#facet-03_modules.modules_graph" "Open modules_graph"